"""Entity-owned, rotatable HMAC attestations for evidence provenance."""
# Generated from the maintained Advisors AI server sources.
# Report issues in this repository; do not edit this file directly.
from __future__ import annotations

import hashlib
import hmac
import json


ENV_NAME = "ENTITY_EVIDENCE_ATTESTATION_KEY"
SECRET_FIELD = "evidence_attestation_key"
# Kept as an explicit invariant because the private service must never mint or
# accept evidence without the code-pinned entity key policy.
POLICY_ENFORCEMENT = True
LEGACY_SCHEME = "entity-hmac-sha256-v1"
ATTESTATION_SCHEME = "entity-hmac-sha256-v2"
LEGACY_ATTESTATION_FIELDS = frozenset({
    "scheme", "kind", "payload_sha256", "signature",
})
ATTESTATION_FIELDS = frozenset({
    "scheme", "kind", "key_id", "policy_version", "payload_sha256",
    "signature",
})


def canonical(payload: dict) -> bytes:
    if not isinstance(payload, dict):
        raise ValueError("attested evidence payload must be an object")
    try:
        return json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (RecursionError, TypeError, ValueError) as exc:
        raise ValueError("attested evidence payload is not canonical JSON") \
            from exc


def _valid_kind(kind: object) -> bool:
    return (
        isinstance(kind, str)
        and bool(kind.strip())
        and kind == kind.strip()
    )


def prove_keyring(*, secret_values: dict | None = None):
    """Resolve all accepted evidence keys and enforce their entity sources."""

    if POLICY_ENFORCEMENT is not True:
        raise RuntimeError("سياسة مفاتيح أدلة الكيان غير مفعلة")
    try:
        from . import order_contract_attestation as key_policy

        # The public resolver loads exactly one pinned policy and one bounded
        # secrets snapshot, then proves every accepted verification key.
        if secret_values is not None:
            raise RuntimeError(
                "public evidence keyring accepts environment values only")
        keyring = key_policy.resolve_keyring()
        for key in keyring.keys:
            if (key.env_name != ENV_NAME
                    and not key.env_name.startswith(ENV_NAME + "_")):
                raise RuntimeError("مصدر بيئة مفتاح الأدلة غير تابع للكيان")
            if (key.secret_field != SECRET_FIELD
                    and not key.secret_field.startswith(SECRET_FIELD + "_")):
                raise RuntimeError("حقل سر مفتاح الأدلة غير تابع للكيان")
        return keyring
    except Exception as exc:  # noqa: BLE001 -- signing must fail closed
        raise RuntimeError("حلقة مفاتيح أدلة الكيان غير مثبتة") from exc


def _resolved_keyring():
    return prove_keyring()


def _key_and_identity() -> tuple[bytes, dict[str, str]]:
    """Return the active material and identity from one proven keyring."""

    keyring = _resolved_keyring()
    active = keyring.active_key()
    identity = {
        "key_id": active.key_id,
        "policy_version": keyring.policy_version,
    }
    return active.material, identity


def _key() -> bytes:
    """Compatibility helper returning only the proven active material."""

    return _key_and_identity()[0]


def key_identity() -> dict[str, str]:
    """Return the identity proven for the exact currently usable keyring."""

    _, identity = _key_and_identity()
    return dict(identity)


def _legacy_signature(*, key: bytes, kind: str, body: bytes) -> str:
    return hmac.new(
        key, kind.encode("utf-8") + b"\0" + body, hashlib.sha256
    ).hexdigest()


def _v2_signature(*, key: bytes, kind: str, key_id: str,
                  policy_version: str, payload_sha256: str,
                  body: bytes) -> str:
    # The signature binds every public identity field and the canonical content
    # itself.  Signing the digest alone would leave the identity envelope open
    # to substitution during key rotation.
    identity = canonical({
        "scheme": ATTESTATION_SCHEME,
        "kind": kind,
        "key_id": key_id,
        "policy_version": policy_version,
        "payload_sha256": payload_sha256,
    })
    message = b"entity-evidence-attestation/v2\0" + identity + b"\0" + body
    return hmac.new(key, message, hashlib.sha256).hexdigest()


def sign(kind: str, payload: dict) -> dict[str, str]:
    """Mint a v2 receipt with the active key of the pinned policy."""

    if not _valid_kind(kind):
        raise RuntimeError("نوع دليل الكيان غير صالح")
    keyring = _resolved_keyring()
    active = keyring.active_key()
    body = canonical(payload)
    payload_sha256 = hashlib.sha256(body).hexdigest()
    attestation = {
        "scheme": ATTESTATION_SCHEME,
        "kind": kind,
        "key_id": active.key_id,
        "policy_version": keyring.policy_version,
        "payload_sha256": payload_sha256,
        "signature": "",
    }
    attestation["signature"] = _v2_signature(
        key=active.material,
        kind=kind,
        key_id=active.key_id,
        policy_version=keyring.policy_version,
        payload_sha256=payload_sha256,
        body=body,
    )
    return attestation


def _verify_v1(*, kind: str, body: bytes, attestation: dict,
               keyring) -> bool:
    if (set(attestation) != LEGACY_ATTESTATION_FIELDS
            or attestation.get("scheme") != LEGACY_SCHEME
            or attestation.get("kind") != kind
            or not isinstance(attestation.get("payload_sha256"), str)
            or not isinstance(attestation.get("signature"), str)):
        return False
    payload_sha256 = hashlib.sha256(body).hexdigest()
    if not hmac.compare_digest(
            attestation["payload_sha256"], payload_sha256):
        return False

    # A v1 receipt has no key identity.  Try every policy-accepted key and only
    # accept one unambiguous match.  Reusing raw material under two key ids is
    # therefore closed instead of silently assigning the receipt an identity.
    matches = 0
    for key_id in keyring.accepted_verification_key_ids:
        key = keyring.key_by_id(key_id)
        if key is None:
            return False
        expected = _legacy_signature(
            key=key.material, kind=kind, body=body)
        matches += int(hmac.compare_digest(
            attestation["signature"], expected))
    return matches == 1


def _verify_v2(*, kind: str, body: bytes, attestation: dict,
               keyring) -> bool:
    if (set(attestation) != ATTESTATION_FIELDS
            or attestation.get("scheme") != ATTESTATION_SCHEME
            or attestation.get("kind") != kind
            or not isinstance(attestation.get("key_id"), str)
            or not isinstance(attestation.get("policy_version"), str)
            or not isinstance(attestation.get("payload_sha256"), str)
            or not isinstance(attestation.get("signature"), str)):
        return False
    key_id = attestation["key_id"]
    policy_version = attestation["policy_version"]
    if (key_id not in keyring.accepted_verification_key_ids
            or policy_version
            not in keyring.accepted_attestation_policy_versions):
        return False
    key = keyring.key_by_id(key_id)
    if key is None:
        return False
    payload_sha256 = hashlib.sha256(body).hexdigest()
    expected_signature = _v2_signature(
        key=key.material,
        kind=kind,
        key_id=key_id,
        policy_version=policy_version,
        payload_sha256=payload_sha256,
        body=body,
    )
    return (
        hmac.compare_digest(
            attestation["payload_sha256"], payload_sha256)
        and hmac.compare_digest(
            attestation["signature"], expected_signature)
    )


def verify(kind: str, payload: dict, attestation: dict | None) -> bool:
    """Verify literal v1 or v2 envelopes against the pinned keyring."""

    try:
        if (not _valid_kind(kind)
                or not isinstance(attestation, dict)):
            return False
        scheme = attestation.get("scheme")
        if scheme not in {LEGACY_SCHEME, ATTESTATION_SCHEME}:
            return False
        body = canonical(payload)
        keyring = _resolved_keyring()
        if scheme == LEGACY_SCHEME:
            return _verify_v1(
                kind=kind, body=body, attestation=attestation,
                keyring=keyring)
        return _verify_v2(
            kind=kind, body=body, attestation=attestation,
            keyring=keyring)
    except (RuntimeError, TypeError, ValueError):
        return False


__all__ = [
    "ATTESTATION_FIELDS",
    "ATTESTATION_SCHEME",
    "ENV_NAME",
    "LEGACY_ATTESTATION_FIELDS",
    "LEGACY_SCHEME",
    "POLICY_ENFORCEMENT",
    "SECRET_FIELD",
    "canonical",
    "key_identity",
    "prove_keyring",
    "sign",
    "verify",
]
