"""Pinned, rotatable HMAC attestations for immutable order contracts.

The active key is selected by a code-pinned policy.  Changing an environment
secret alone cannot silently create a new signing identity: its material
fingerprint must match the active key entry.  An explicit policy rotation adds
the new active key while retaining old entries as verification-only keys.
"""
# Generated from the maintained Advisors AI server sources.
# Report issues in this repository; do not edit this file directly.

from __future__ import annotations

import hashlib
import hmac
import json
import os
import re
import stat
from copy import deepcopy
from dataclasses import dataclass, field
from pathlib import Path
from types import MappingProxyType
from typing import Any


POLICY_PATH = Path(__file__).with_name(
    "order_contract_key_policy.json")
POLICY_SCHEMA = "order-contract-key-policy/v1"
ATTESTATION_SCHEME = "order-contract-hmac-sha256/v1"
TRUSTED_POLICY_FINGERPRINTS = MappingProxyType({
    "2026-08-04.1":
        "0eb408efc3122c7ea0055e2385d93cd7116d1ea0ff7aa772b812d513906f5676",
})
_POLICY_FIELDS = frozenset({
    "schema",
    "version",
    "active_signing_key_id",
    "accepted_verification_key_ids",
    "accepted_attestation_policy_versions",
    "keys",
})
_KEY_FIELDS = frozenset({
    "key_id",
    "env_name",
    "secret_field",
    "material_sha256",
    "usage",
})
_ATTESTATION_FIELDS = frozenset({
    "scheme",
    "kind",
    "key_id",
    "policy_version",
    "payload_sha256",
    "signature",
})
_VERSION = re.compile(r"^\d{4}-\d{2}-\d{2}\.\d+$")
_KEY_ID = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
_ENV_NAME = re.compile(r"^[A-Z][A-Z0-9_]{2,127}$")
_SECRET_FIELD = re.compile(r"^[a-z][a-z0-9_]{2,127}$")
_HEX64 = re.compile(r"^[0-9a-f]{64}$")
_MAX_POLICY_BYTES = 128 * 1024
_MAX_KEY_MATERIAL_CHARS = 4096


class KeyPolicyError(RuntimeError):
    """The key policy is absent, malformed, unpinned or contradictory."""


class KeyUnavailableError(KeyPolicyError):
    """A pinned key's secret material is unavailable or does not match."""


@dataclass(frozen=True)
class ResolvedKey:
    """One policy-pinned key whose material was proven in one snapshot."""

    key_id: str
    env_name: str
    secret_field: str
    usage: str
    material: bytes = field(repr=False)


@dataclass(frozen=True)
class ResolvedKeyring:
    """Immutable, fully proven keyring for one pinned policy snapshot."""

    policy_version: str
    active_signing_key_id: str
    accepted_verification_key_ids: tuple[str, ...]
    accepted_attestation_policy_versions: tuple[str, ...]
    keys: tuple[ResolvedKey, ...]

    def key_by_id(self, key_id: str) -> ResolvedKey | None:
        for key in self.keys:
            if key.key_id == key_id:
                return key
        return None

    def active_key(self) -> ResolvedKey:
        key = self.key_by_id(self.active_signing_key_id)
        if key is None or key.usage != "sign_and_verify":
            raise KeyPolicyError("active signing key is unavailable")
        return key

    def identity(self) -> dict[str, Any]:
        """Return a detached, non-secret statement of the proven snapshot."""

        return {
            "key_id": self.active_signing_key_id,
            "policy_version": self.policy_version,
            "accepted_verification_key_ids": list(
                self.accepted_verification_key_ids),
        }


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise KeyPolicyError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def canonical(payload: dict[str, Any]) -> bytes:
    if not isinstance(payload, dict):
        raise KeyPolicyError("attested payload must be an object")
    try:
        return json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise KeyPolicyError("attested payload is not canonical JSON") from exc


def _read_json(path: Path, maximum: int, label: str) -> dict[str, Any]:
    fd: int | None = None
    try:
        metadata = path.lstat()
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise KeyPolicyError(f"{label} path is not a regular file")
        if metadata.st_size <= 0 or metadata.st_size > maximum:
            raise KeyPolicyError(f"{label} size is invalid")
        flags = os.O_RDONLY
        if hasattr(os, "O_BINARY"):
            flags |= os.O_BINARY
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        fd = os.open(path, flags)
        opened = os.fstat(fd)
        if not stat.S_ISREG(opened.st_mode):
            raise KeyPolicyError(f"{label} changed while opening")
        if ((metadata.st_dev, metadata.st_ino)
                != (opened.st_dev, opened.st_ino)):
            raise KeyPolicyError(f"{label} was replaced while opening")
        if opened.st_size <= 0 or opened.st_size > maximum:
            raise KeyPolicyError(f"{label} size changed while opening")
        chunks: list[bytes] = []
        remaining = maximum + 1
        while remaining > 0:
            chunk = os.read(fd, min(1024 * 1024, remaining))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        raw_bytes = b"".join(chunks)
        if len(raw_bytes) > maximum or os.read(fd, 1):
            raise KeyPolicyError(f"{label} exceeds the size limit")
        raw = raw_bytes.decode("utf-8")
        parsed = json.loads(raw, object_pairs_hook=_strict_object)
    except KeyPolicyError:
        raise
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise KeyPolicyError(f"{label} is unavailable or malformed") from exc
    finally:
        if fd is not None:
            try:
                os.close(fd)
            except OSError:
                pass
    if not isinstance(parsed, dict):
        raise KeyPolicyError(f"{label} root must be an object")
    return parsed


def policy_fingerprint(policy: dict[str, Any]) -> str:
    return hashlib.sha256(canonical(policy)).hexdigest()


def material_fingerprint(key_id: str, secret: str | bytes) -> str:
    if not isinstance(key_id, str) or not _KEY_ID.fullmatch(key_id):
        raise KeyPolicyError("key id is invalid")
    if isinstance(secret, str):
        material = secret.encode("utf-8")
    elif isinstance(secret, bytes):
        material = secret
    else:
        raise KeyUnavailableError("key material type is invalid")
    return hashlib.sha256(
        b"order-contract-key/v1\0" + key_id.encode("ascii") + b"\0" + material
    ).hexdigest()


def load_policy(path: str | Path | None = None) -> dict[str, Any]:
    policy = _read_json(
        Path(path) if path is not None else POLICY_PATH,
        _MAX_POLICY_BYTES,
        "order contract key policy",
    )
    if set(policy) != _POLICY_FIELDS:
        raise KeyPolicyError("order contract key policy fields mismatch")
    if policy.get("schema") != POLICY_SCHEMA:
        raise KeyPolicyError("order contract key policy schema is unsupported")
    version = policy.get("version")
    if not isinstance(version, str) or not _VERSION.fullmatch(version):
        raise KeyPolicyError("order contract key policy version is invalid")
    trusted = TRUSTED_POLICY_FINGERPRINTS.get(version)
    measured = policy_fingerprint(policy)
    if trusted is None or not hmac.compare_digest(measured, trusted):
        raise KeyPolicyError("order contract key policy is not pinned by this build")

    active = policy.get("active_signing_key_id")
    if not isinstance(active, str) or not _KEY_ID.fullmatch(active):
        raise KeyPolicyError("active signing key id is invalid")
    accepted = policy.get("accepted_verification_key_ids")
    accepted_versions = policy.get("accepted_attestation_policy_versions")
    if (not isinstance(accepted, list) or not accepted
            or any(not isinstance(item, str) or not _KEY_ID.fullmatch(item)
                   for item in accepted)
            or len(set(accepted)) != len(accepted)):
        raise KeyPolicyError("accepted verification key ids are invalid")
    if (not isinstance(accepted_versions, list) or not accepted_versions
            or any(not isinstance(item, str) or not _VERSION.fullmatch(item)
                   for item in accepted_versions)
            or len(set(accepted_versions)) != len(accepted_versions)
            or version not in accepted_versions):
        raise KeyPolicyError("accepted attestation policy versions are invalid")

    raw_keys = policy.get("keys")
    if not isinstance(raw_keys, list) or not raw_keys:
        raise KeyPolicyError("order contract keyring is empty")
    keys: dict[str, dict[str, Any]] = {}
    active_usage_count = 0
    for entry in raw_keys:
        if not isinstance(entry, dict) or set(entry) != _KEY_FIELDS:
            raise KeyPolicyError("order contract key entry fields mismatch")
        key_id = entry.get("key_id")
        env_name = entry.get("env_name")
        secret_field = entry.get("secret_field")
        material_sha = entry.get("material_sha256")
        usage = entry.get("usage")
        if not isinstance(key_id, str) or not _KEY_ID.fullmatch(key_id):
            raise KeyPolicyError("order contract key id is invalid")
        if key_id in keys:
            raise KeyPolicyError("order contract key id is duplicated")
        if not isinstance(env_name, str) or not _ENV_NAME.fullmatch(env_name):
            raise KeyPolicyError(f"{key_id}: environment source is invalid")
        if (not isinstance(secret_field, str)
                or not _SECRET_FIELD.fullmatch(secret_field)):
            raise KeyPolicyError(f"{key_id}: secret field is invalid")
        if (not isinstance(material_sha, str)
                or not _HEX64.fullmatch(material_sha)):
            raise KeyPolicyError(f"{key_id}: material fingerprint is invalid")
        if usage not in {"sign_and_verify", "verify_only"}:
            raise KeyPolicyError(f"{key_id}: key usage is invalid")
        active_usage_count += int(usage == "sign_and_verify")
        keys[key_id] = deepcopy(entry)
    if (set(accepted) != set(keys) or active not in keys
            or keys[active]["usage"] != "sign_and_verify"
            or active_usage_count != 1):
        raise KeyPolicyError("active and accepted keyring roles are contradictory")
    return deepcopy(policy)


def _entry_by_id(policy: dict[str, Any], key_id: str) -> dict[str, Any]:
    for entry in policy["keys"]:
        if entry["key_id"] == key_id:
            return entry
    raise KeyPolicyError("attestation key id is not present in the current policy")


def _validated_material(entry: dict[str, Any], value: Any) -> bytes:
    if (not isinstance(value, str) or len(value) < 32
            or len(value) > _MAX_KEY_MATERIAL_CHARS):
        raise KeyUnavailableError(
            f"key material for {entry['key_id']} is unavailable")
    measured = material_fingerprint(entry["key_id"], value)
    if not hmac.compare_digest(measured, entry["material_sha256"]):
        raise KeyUnavailableError(
            f"key material for {entry['key_id']} does not match its policy pin")
    return value.encode("utf-8")


def resolve_keyring(
        *, secret_values: dict[str, Any] | None = None,
        secrets_path: str | Path | None = None,
        expected_active_env_name: str | None = None,
        expected_active_secret_field: str | None = None) -> ResolvedKeyring:
    """Resolve and prove every accepted key from one pinned policy snapshot.

    The public package captures every policy-declared environment value in
    one snapshot. File and caller-supplied secret fallbacks are rejected.
    The policy is loaded exactly once, so callers never combine identities
    from two policy revisions during a rotation.
    """

    if secret_values is not None or secrets_path is not None:
        raise KeyUnavailableError(
            "public keyring accepts environment values only")

    policy = load_policy()
    entries = [
        _entry_by_id(policy, key_id)
        for key_id in policy["accepted_verification_key_ids"]
    ]
    active_entry = _entry_by_id(
        policy, policy["active_signing_key_id"])
    if (expected_active_env_name is not None
            and active_entry["env_name"] != expected_active_env_name):
        raise KeyPolicyError("active key environment source mismatch")
    if (expected_active_secret_field is not None
            and active_entry["secret_field"]
            != expected_active_secret_field):
        raise KeyPolicyError("active key secret source mismatch")

    environment_snapshot = dict(os.environ)
    values_by_id: dict[str, Any] = {
        entry["key_id"]: environment_snapshot.get(
            entry["env_name"], "")
        for entry in entries
    }

    keys = tuple(
        ResolvedKey(
            key_id=entry["key_id"],
            env_name=entry["env_name"],
            secret_field=entry["secret_field"],
            usage=entry["usage"],
            material=_validated_material(
                entry, values_by_id[entry["key_id"]]),
        )
        for entry in entries
    )
    keyring = ResolvedKeyring(
        policy_version=policy["version"],
        active_signing_key_id=policy["active_signing_key_id"],
        accepted_verification_key_ids=tuple(
            policy["accepted_verification_key_ids"]),
        accepted_attestation_policy_versions=tuple(
            policy["accepted_attestation_policy_versions"]),
        keys=keys,
    )
    keyring.active_key()
    return keyring


def _signature(*, key: bytes, key_id: str, policy_version: str,
               kind: str, body: bytes) -> str:
    message = (
        ATTESTATION_SCHEME.encode("ascii") + b"\0"
        + key_id.encode("ascii") + b"\0"
        + policy_version.encode("ascii") + b"\0"
        + kind.encode("utf-8") + b"\0" + body
    )
    return hmac.new(key, message, hashlib.sha256).hexdigest()


def sign(kind: str, payload: dict[str, Any]) -> dict[str, str]:
    if not isinstance(kind, str) or not kind.strip() or kind != kind.strip():
        raise KeyPolicyError("attestation kind is invalid")
    keyring = resolve_keyring()
    active = keyring.active_key()
    body = canonical(payload)
    return {
        "scheme": ATTESTATION_SCHEME,
        "kind": kind,
        "key_id": active.key_id,
        "policy_version": keyring.policy_version,
        "payload_sha256": hashlib.sha256(body).hexdigest(),
        "signature": _signature(
            key=active.material,
            key_id=active.key_id,
            policy_version=keyring.policy_version,
            kind=kind,
            body=body,
        ),
    }


def assert_active_key_ready(
        *, expected_env_name: str | None = None,
        expected_secret_field: str | None = None,
        secret_values: dict[str, Any] | None = None) -> dict[str, str]:
    """Fail closed before side effects if the pinned active key is unusable.

    A caller that consumes the same key through a fixed legacy source may pin
    that source here.  The checks happen against the same already-validated
    policy object used to resolve the key, avoiding a second policy read and a
    readiness/signing split-brain during rotation.
    """
    keyring = resolve_keyring(
        secret_values=secret_values,
        expected_active_env_name=expected_env_name,
        expected_active_secret_field=expected_secret_field,
    )
    return {
        "key_id": keyring.active_signing_key_id,
        "policy_version": keyring.policy_version,
    }


def verify(kind: str, payload: dict[str, Any], attestation: object) -> bool:
    try:
        if (not isinstance(kind, str) or not kind.strip()
                or kind != kind.strip()
                or not isinstance(attestation, dict)
                or set(attestation) != _ATTESTATION_FIELDS):
            return False
        keyring = resolve_keyring()
        if (attestation.get("scheme") != ATTESTATION_SCHEME
                or attestation.get("kind") != kind):
            return False
        key_id = attestation.get("key_id")
        policy_version = attestation.get("policy_version")
        if (key_id not in keyring.accepted_verification_key_ids
                or policy_version
                not in keyring.accepted_attestation_policy_versions):
            return False
        key = keyring.key_by_id(key_id)
        if key is None:
            return False
        body = canonical(payload)
        expected_payload_sha = hashlib.sha256(body).hexdigest()
        expected_signature = _signature(
            key=key.material,
            key_id=key_id,
            policy_version=policy_version,
            kind=kind,
            body=body,
        )
        return (
            isinstance(attestation.get("payload_sha256"), str)
            and isinstance(attestation.get("signature"), str)
            and hmac.compare_digest(
                attestation["payload_sha256"], expected_payload_sha)
            and hmac.compare_digest(
                attestation["signature"], expected_signature)
        )
    except (KeyPolicyError, OSError, TypeError, ValueError):
        return False


def policy_identity() -> dict[str, Any]:
    """Expose non-secret policy identity for readiness probes."""
    policy = load_policy()
    return {
        "schema": policy["schema"],
        "version": policy["version"],
        "active_signing_key_id": policy["active_signing_key_id"],
        "accepted_verification_key_ids": list(
            policy["accepted_verification_key_ids"]),
    }


__all__ = [
    "ATTESTATION_SCHEME",
    "KeyPolicyError",
    "KeyUnavailableError",
    "POLICY_SCHEMA",
    "ResolvedKey",
    "ResolvedKeyring",
    "canonical",
    "assert_active_key_ready",
    "load_policy",
    "material_fingerprint",
    "policy_fingerprint",
    "policy_identity",
    "resolve_keyring",
    "sign",
    "verify",
]
