# Generated from the maintained Advisors AI server sources.
# Report issues in this repository; do not edit this file directly.
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""HMAC-authenticated, transient capsule for one public-page readiness miss.

Only ``public_readiness_check/v2`` may create a capsule.  The caller cannot
choose consent, provenance, a recheck URL, or commercial content.  The two
receipts are issued here and bind the sanitised target, complete measurement,
selected signal, destination surface, and a short life.

The capsule is a response to the requester.  It is never permission for cold
outreach, persistence, sharing, or aggregation.
"""
from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import os
import re
import secrets
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

from . import evidence_attestation as attest
from .public_readiness_check import (
    CONTRACT_KEYS as CHECK_KEYS,
    MEASUREMENT,
    NOT_MEASURED,
    SCHEMA as CHECK_SCHEMA,
    SCOPE,
    REQUIRED_SIGNAL_KEYS,
    SIGNAL_WEIGHT_CONTRACT,
    check_public_page,
)

SCHEMA = "advisorsai.proof_capsule/v2"
RECEIPT_SCHEMA = "advisorsai.transient_receipt/v1"
SOURCE_KIND = "store-readiness-source/v1"
CONSENT_KIND = "store-readiness-request/v1"
REVOCATION_KIND = "store-readiness-revocation/v1"
RECHECK_URL = "https://advisorsai.ai/store-readiness/recheck"
OFFER_URLS = {
    "ar": "https://advisorsai.ai/service.html?service=store-audit",
    "en": "https://advisorsai.ai/en-service.html?service=store-audit",
}
# Backward-compatible Arabic alias for callers that only test isolation.
OFFER_URL = OFFER_URLS["ar"]
SURFACES = ("claude-connector", "mcp-registry", "openai-isolated")
ISOLATED_SURFACE = "openai-isolated"
RECEIPT_TTL = timedelta(minutes=15)
MAX_CHECK_AGE = timedelta(minutes=30)
_REVOCATION_CONFIG = os.environ.get("ADVISORS_PROOF_REVOCATION_LEDGER", "").strip()
REVOCATION_LEDGER = (
    Path(_REVOCATION_CONFIG)
    if _REVOCATION_CONFIG
    else Path("proof-capsule-revocations.jsonl")
)

CAPSULE_FIELDS = frozenset({
    "schema", "surface", "language", "target", "finding", "evidence", "imperative",
    "acceptance", "recheck_url", "offer_url", "consent_receipt",
    "source_receipt", "permissions", "built_at_utc", "expires_at_utc",
})
FINDING_FIELDS = frozenset({
    "signal_key", "label", "methodology_reference",
})
EVIDENCE_FIELDS = frozenset({
    "measurement", "result", "score_percent", "coverage_percent",
    "measured_at_utc",
})
PERMISSION_FIELDS = frozenset({
    "scan_public_url", "display_to_requester", "store_result",
    "share_result", "aggregate_result", "delete_at_utc",
})
SOURCE_FIELDS = frozenset({
    "schema", "receipt_id", "source_token", "target_sha256",
    "target_origin", "measurement_sha256", "check_schema", "measurement",
    "signal_key", "result", "score_percent", "coverage_percent",
    "measured_at_utc", "language", "purpose", "scan_public_url",
    "display_to_requester", "store_result", "share_result",
    "aggregate_result", "surface",
    "issued_at_utc", "expires_at_utc", "delete_at_utc", "attestation",
})
CONSENT_FIELDS = frozenset({
    "schema", "receipt_id", "consent_state", "purpose", "target_sha256",
    "target_origin", "language", "scan_public_url", "display_to_requester",
    "store_result", "share_result", "aggregate_result", "surface",
    "issued_at_utc", "expires_at_utc",
    "delete_at_utc", "attestation",
})
SIGNAL_FIELDS = frozenset({"key", "ok", "detail", "weight", "evidence"})
TRANSPORT_FIELDS = frozenset({
    "timeout_seconds", "max_url_chars", "max_body_bytes", "max_redirects",
    "max_html_bytes", "max_html_fact_bytes", "html_parse_timeout_seconds",
})
REVOCATION_FIELDS = frozenset({
    "schema", "receipt_id_sha256", "revoked_at_utc", "delete_at_utc",
    "attestation",
})
HEX64 = re.compile(r"[0-9a-f]{64}\Z")
TOKEN = re.compile(r"[A-Za-z0-9_-]{16,96}\Z")
SAFE_HOST = re.compile(r"[A-Za-z0-9.-]{1,253}\Z")
SAFE_PATH = re.compile(r"/[A-Za-z0-9._~!$&'()*+,;=:@%/-]{0,1024}\Z")
BAD_TEXT = re.compile(r"<|>|\x1b|[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
PII = re.compile(
    r"[\w.+-]+@[\w-]+\.[\w.-]+|(?<!\d)(?:\+?\d[\s().-]?){9,15}(?!\d)"
)
SIGNED_PERMISSIONS = {
    "scan_public_url": True,
    "display_to_requester": True,
    "store_result": False,
    "share_result": False,
    "aggregate_result": False,
}
_TRUSTED_CHECK_SEAL = object()

# Fixed editorial order, not a severity scale.  A failed signal is eligible
# only after the full checker contract has completed and been revalidated.
REMEDIES: dict[str, tuple[str, str, str]] = {
    "title": (
        "عنوان الصفحة غير كافٍ للقراءة الآلية",
        "أضف عنواناً وصفياً واحداً للصفحة يسمّي ما تقدمه بوضوح.",
        "يعيد الفحص إشارة title بقيمة ناجحة للمسار نفسه.",
    ),
    "description": (
        "وصف الصفحة التعريفي غير متاح",
        "أضف وصفاً تعريفياً موجزاً ودقيقاً لما تقدمه الصفحة.",
        "يعيد الفحص إشارة description بقيمة ناجحة للمسار نفسه.",
    ),
    "h1": (
        "العنوان الرئيسي للصفحة غير منضبط",
        "ضع عنوان H1 واحداً واضحاً يصف موضوع الصفحة.",
        "يعيد الفحص إشارة h1 بقيمة ناجحة للمسار نفسه.",
    ),
    "structured_business": (
        "بيانات تعريف النشاط المنظمة غير متاحة",
        "أضف بيانات منظمة صحيحة تعرّف النشاط باسمه ونوعه.",
        "يعيد الفحص إشارة structured_business بقيمة ناجحة للمسار نفسه.",
    ),
    "structured_offering": (
        "بيانات العرض المنظمة غير متاحة",
        "أضف بيانات منظمة صحيحة تصف المنتج أو الخدمة المعروضة.",
        "يعيد الفحص إشارة structured_offering بقيمة ناجحة للمسار نفسه.",
    ),
    "canonical": (
        "الرابط المعياري للصفحة غير متاح",
        "أضف رابطاً معيارياً واحداً يشير إلى النسخة المعتمدة من الصفحة.",
        "يعيد الفحص إشارة canonical بقيمة ناجحة للمسار نفسه.",
    ),
    "sitemap": (
        "خريطة الموقع القابلة للقراءة الآلية غير متاحة",
        "ضع خريطة موقع صالحة في المسار المعلن للموقع.",
        "يعيد الفحص إشارة sitemap بقيمة ناجحة للموقع نفسه.",
    ),
    "jsonld_valid": (
        "بيانات JSON-LD المنشورة غير صالحة",
        "أصلح بنية JSON-LD حتى تمر جميع الكتل من محلل JSON.",
        "لا يعيد الفحص إشارة jsonld_valid راسبة للمسار نفسه.",
    ),
    "robots": (
        "سياسة الزحف المعلنة تحجب المسار المفحوص",
        "عدّل سياسة robots للمسار المقصود بما يوافق قرارك المنشور للزحف.",
        "يعيد الفحص إشارة robots بقيمة ناجحة للمسار نفسه.",
    ),
}
REMEDIES_EN: dict[str, tuple[str, str, str]] = {
    "title": (
        "The page title is not machine-readable enough",
        "Add one descriptive page title that clearly names the offering.",
        "A recheck returns a passing title signal for the same path.",
    ),
    "description": (
        "The page has no usable meta description",
        "Add a concise, accurate meta description of the page offering.",
        "A recheck returns a passing description signal for the same path.",
    ),
    "h1": (
        "The page primary heading is not well formed",
        "Use exactly one clear H1 heading that describes the page topic.",
        "A recheck returns a passing h1 signal for the same path.",
    ),
    "structured_business": (
        "Machine-readable business identity data is missing",
        "Add valid structured data that identifies the business by name and type.",
        "A recheck returns a passing structured_business signal for the same path.",
    ),
    "structured_offering": (
        "Machine-readable offering data is missing",
        "Add valid structured data that describes the product or service offered.",
        "A recheck returns a passing structured_offering signal for the same path.",
    ),
    "canonical": (
        "The page has no usable canonical URL",
        "Add one canonical link to the authoritative version of the page.",
        "A recheck returns a passing canonical signal for the same path.",
    ),
    "sitemap": (
        "A machine-readable sitemap is unavailable",
        "Publish a valid sitemap at the site's declared sitemap location.",
        "A recheck returns a passing sitemap signal for the same site.",
    ),
    "jsonld_valid": (
        "Published JSON-LD is malformed",
        "Fix the JSON-LD syntax until every block parses as valid JSON.",
        "A recheck no longer returns a failing jsonld_valid signal for the same path.",
    ),
    "robots": (
        "The declared crawler policy blocks the checked path",
        "Adjust the robots policy for this path to match your published crawl decision.",
        "A recheck returns a passing robots signal for the same path.",
    ),
}
METHOD_REFS: dict[str, dict[str, Any] | None] = {
    "title": {"point": 21, "relation": "partial"},
    "description": {"point": 21, "relation": "partial"},
    "h1": {"point": 22, "relation": "partial"},
    "sitemap": {"point": 24, "relation": "partial"},
    # Point 27 measures a named offering, not the presence of an Organization
    # entity.  Do not manufacture a catalogue reference for a signal that the
    # published methodology does not cover directly.
    "structured_business": None,
    "structured_offering": {"point": 27, "relation": "partial"},
    "canonical": None,
    "jsonld_valid": None,
    "robots": None,
}


def _utc(now: datetime | None = None) -> datetime:
    value = now or datetime.now(timezone.utc)
    if value.tzinfo is None:
        raise ValueError("now must be timezone-aware")
    return value.astimezone(timezone.utc).replace(microsecond=0)


def _stamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _parse_stamp(value: object) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        parsed = datetime.fromisoformat(
            value[:-1] + "+00:00" if value.endswith("Z") else value
        )
    except ValueError:
        return None
    if parsed.tzinfo is None or parsed.utcoffset() != timedelta(0):
        return None
    return parsed.astimezone(timezone.utc).replace(microsecond=0)


def _sha_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _sha_json(value: dict) -> str:
    return hashlib.sha256(attest.canonical(value)).hexdigest()


def _clean_url(value: object) -> str | None:
    """Return scheme+public-looking host+path only; never query/userinfo."""
    if not isinstance(value, str) or len(value) > 2048 or BAD_TEXT.search(value):
        return None
    try:
        parsed = urlsplit(value.strip())
        port = parsed.port
    except ValueError:
        return None
    if parsed.scheme.lower() not in {"http", "https"}:
        return None
    if parsed.username is not None or parsed.password is not None:
        return None
    host = (parsed.hostname or "").lower().rstrip(".")
    if (
        not SAFE_HOST.fullmatch(host)
        or host == "localhost"
        or host.endswith((".local", ".internal", ".localhost"))
        or PII.search(host)
    ):
        return None
    try:
        address = ipaddress.ip_address(host)
    except ValueError:
        address = None
    if address is not None and not address.is_global:
        return None
    if port is not None and port not in {80, 443}:
        return None
    path = parsed.path or "/"
    if not SAFE_PATH.fullmatch(path) or ".." in path.split("/"):
        return None
    netloc = host + (f":{port}" if port is not None else "")
    return urlunsplit((parsed.scheme.lower(), netloc, path, "", ""))


def _origin(value: object) -> str | None:
    cleaned = _clean_url(value)
    if not cleaned:
        return None
    parsed = urlsplit(cleaned)
    return urlunsplit((parsed.scheme, parsed.netloc, "/", "", ""))


def _safe_human(value: object, *, max_len: int = 600) -> bool:
    return (
        isinstance(value, str)
        and 0 < len(value) <= max_len
        and not BAD_TEXT.search(value)
        and not PII.search(value)
    )


def _closed_check(check: object, now: datetime) -> list[str]:
    out: list[str] = []
    if not isinstance(check, dict):
        return ["check ليس كائناً"]
    if set(check) != set(CHECK_KEYS):
        out.append("مخطط check غير مغلق")
        return out
    if check.get("schema") != CHECK_SCHEMA:
        out.append("مخطط الفاحص غير معتمد")
    if check.get("execution_ok") is not True or check.get("ok") is not True:
        out.append("الفحص لم يكتمل")
    if check.get("status") != "complete" or check.get("measurement") != MEASUREMENT:
        out.append("حالة القياس أو نوعه غير معتمد")
    if check.get("errors") != []:
        out.append("الفحص الكامل يحمل أخطاء")
    cleaned = _clean_url(check.get("checked_url"))
    if cleaned is None or cleaned != check.get("checked_url"):
        out.append("checked_url غير منظف")
    if _origin(cleaned) != check.get("checked_origin"):
        out.append("checked_origin لا يطابق الهدف")
    for key in ("score_percent", "coverage_percent", "weighted_miss_count",
                "note_miss_count", "unchecked_count"):
        if type(check.get(key)) is not int:
            out.append(f"{key} ليس عدداً صحيحاً")
    score = check.get("score_percent")
    coverage = check.get("coverage_percent")
    if type(score) is int and not 0 <= score <= 100:
        out.append("score_percent خارج المدى")
    if coverage != 100 or check.get("unchecked_count") != 0:
        out.append("التغطية ليست مكتملة")
    signals = check.get("signals")
    seen: dict[str, dict] = {}
    if not isinstance(signals, list):
        out.append("signals ليست قائمة")
        signals = []
    for signal in signals:
        if not isinstance(signal, dict) or set(signal) != SIGNAL_FIELDS:
            out.append("إشارة خارج المخطط المغلق")
            continue
        key = signal.get("key")
        if key not in SIGNAL_WEIGHT_CONTRACT or key in seen:
            out.append("إشارة مجهولة أو مكررة")
            continue
        if type(signal.get("ok")) is not bool:
            out.append(f"إشارة {key} غير محسومة")
        if type(signal.get("weight")) is not int or signal.get("weight") != SIGNAL_WEIGHT_CONTRACT[key]:
            out.append(f"وزن إشارة {key} غير مطابق")
        if not isinstance(signal.get("detail"), str) or not signal["detail"].strip() or len(signal["detail"]) > 300 or BAD_TEXT.search(signal["detail"]):
            out.append(f"تفصيل إشارة {key} غير آمن")
        evidence = signal.get("evidence")
        if not isinstance(evidence, str) or len(evidence) > 128 or BAD_TEXT.search(evidence):
            out.append(f"دليل إشارة {key} غير آمن")
        seen[key] = signal
    if not REQUIRED_SIGNAL_KEYS <= set(seen):
        out.append("إشارات مطلوبة مفقودة")
    if not set(seen) <= set(SIGNAL_WEIGHT_CONTRACT):
        out.append("إشارات زائدة")
    optional = seen.get("jsonld_valid")
    if optional is not None and optional.get("ok") is not False:
        out.append("تشخيص jsonld_valid الاختياري غير راسب")
    if seen:
        total = sum(row["weight"] for row in seen.values())
        got = sum(row["weight"] for row in seen.values() if row.get("ok") is True)
        expected_score = round(100 * got / total) if total else 0
        weighted_misses = sum(1 for row in seen.values() if row.get("ok") is False and row["weight"] > 0)
        note_misses = sum(1 for row in seen.values() if row.get("ok") is False and row["weight"] == 0)
        if score != expected_score:
            out.append("درجة الفحص لا تطابق الإشارات")
        if check.get("weighted_miss_count") != weighted_misses:
            out.append("عدد العيوب الموزونة غير مطابق")
        if check.get("note_miss_count") != note_misses:
            out.append("عدد الملاحظات غير مطابق")
        expected_ready = expected_score == 100 and weighted_misses == 0
        if check.get("readiness_passed") is not expected_ready:
            out.append("readiness_passed غير مشتق من القياس")
    if check.get("scope") != SCOPE or check.get("not_measured") != list(NOT_MEASURED):
        out.append("حدود القياس تغيرت")
    limits = check.get("selected_transport_limits")
    if not isinstance(limits, dict) or set(limits) != TRANSPORT_FIELDS or any(
            type(value) not in {int, float} or isinstance(value, bool) or value <= 0
            for value in (limits or {}).values()):
        out.append("حدود النقل غير مطابقة")
    measured = _parse_stamp(check.get("measured_at_utc"))
    if measured is None or measured > now + timedelta(minutes=2) or now - measured > MAX_CHECK_AGE:
        out.append("زمن القياس غير صالح أو قديم")
    return out


def _signed(kind: str, fields: dict[str, Any]) -> dict[str, Any]:
    return {**fields, "attestation": attest.sign(kind, fields)}


def _receipt_base(receipt: object, fields: frozenset[str]) -> dict | None:
    if not isinstance(receipt, dict) or set(receipt) != fields:
        return None
    return {key: value for key, value in receipt.items() if key != "attestation"}


def receipt_revoked(receipt_id: object, path: Path | None = None) -> bool:
    if not isinstance(receipt_id, str):
        return True
    ledger = path or REVOCATION_LEDGER
    if not ledger.is_file():
        return False
    wanted = _sha_text(receipt_id)
    try:
        lines = ledger.read_text(encoding="utf-8", errors="strict").splitlines()
    except (OSError, UnicodeError):
        return True
    for line in lines:
        try:
            row = json.loads(line)
        except (json.JSONDecodeError, TypeError):
            return True
        if not isinstance(row, dict) or set(row) != REVOCATION_FIELDS:
            return True
        base = {key: value for key, value in row.items() if key != "attestation"}
        if (
            base.get("schema") != RECEIPT_SCHEMA
            or not HEX64.fullmatch(str(base.get("receipt_id_sha256") or ""))
            or _parse_stamp(base.get("revoked_at_utc")) is None
            or _parse_stamp(base.get("delete_at_utc")) is None
            or not attest.verify(
                REVOCATION_KIND, base, row.get("attestation")
            )
        ):
            return True
        if base["receipt_id_sha256"] == wanted:
            return True
    return False


def _valid_time_window(receipt: dict, now: datetime) -> bool:
    issued = _parse_stamp(receipt.get("issued_at_utc"))
    expires = _parse_stamp(receipt.get("expires_at_utc"))
    deleted = _parse_stamp(receipt.get("delete_at_utc"))
    return bool(
        issued and expires and deleted
        and deleted == expires
        and issued <= now + timedelta(minutes=2)
        and issued < expires
        and now < expires
        and expires - issued <= RECEIPT_TTL
    )


def _valid_signed_permissions(receipt: dict) -> bool:
    return all(receipt.get(key) is value for key, value in SIGNED_PERMISSIONS.items())


def verify_source_receipt(
    receipt: object, *, target_url: str | None = None,
    surface: str | None = None, signal_key: str | None = None,
    language: str | None = None,
    now: datetime | None = None, revocations_path: Path | None = None,
) -> bool:
    base = _receipt_base(receipt, SOURCE_FIELDS)
    if base is None or base.get("schema") != RECEIPT_SCHEMA:
        return False
    moment = _utc(now)
    if not attest.verify(SOURCE_KIND, base, receipt.get("attestation")):
        return False
    if not _valid_time_window(base, moment) or receipt_revoked(base.get("receipt_id"), revocations_path):
        return False
    if not TOKEN.fullmatch(str(base.get("receipt_id") or "")) or not TOKEN.fullmatch(str(base.get("source_token") or "")):
        return False
    if not HEX64.fullmatch(str(base.get("target_sha256") or "")) or not HEX64.fullmatch(str(base.get("measurement_sha256") or "")):
        return False
    if (
        base.get("check_schema") != CHECK_SCHEMA
        or base.get("measurement") != MEASUREMENT
        or base.get("language") not in {"ar", "en"}
        or base.get("result") != "miss"
        or base.get("purpose") != "transient-public-page-proof"
        or not _valid_signed_permissions(base)
    ):
        return False
    if base.get("surface") not in SURFACES or _origin(base.get("target_origin")) != base.get("target_origin"):
        return False
    if base.get("signal_key") not in REMEDIES:
        return False
    if type(base.get("score_percent")) is not int or type(base.get("coverage_percent")) is not int:
        return False
    measured = _parse_stamp(base.get("measured_at_utc"))
    if measured is None or measured > moment + timedelta(minutes=2) or moment - measured > MAX_CHECK_AGE:
        return False
    if surface is not None and base.get("surface") != surface:
        return False
    if signal_key is not None and base.get("signal_key") != signal_key:
        return False
    if language is not None and base.get("language") != language:
        return False
    if target_url is not None:
        cleaned = _clean_url(target_url)
        if cleaned is None or not secrets.compare_digest(_sha_text(cleaned), base["target_sha256"]):
            return False
    return True


def verify_consent_receipt(
    receipt: object, *, surface: str | None = None,
    language: str | None = None, now: datetime | None = None,
    revocations_path: Path | None = None,
) -> bool:
    base = _receipt_base(receipt, CONSENT_FIELDS)
    if base is None or base.get("schema") != RECEIPT_SCHEMA:
        return False
    moment = _utc(now)
    if not attest.verify(CONSENT_KIND, base, receipt.get("attestation")):
        return False
    if not _valid_time_window(base, moment) or receipt_revoked(base.get("receipt_id"), revocations_path):
        return False
    if not TOKEN.fullmatch(str(base.get("receipt_id") or "")) or not HEX64.fullmatch(str(base.get("target_sha256") or "")):
        return False
    if (
        base.get("consent_state") != "request-submitted"
        or base.get("purpose") != "transient-public-page-check"
        or base.get("language") not in {"ar", "en"}
        or not _valid_signed_permissions(base)
    ):
        return False
    if base.get("surface") not in SURFACES or _origin(base.get("target_origin")) != base.get("target_origin"):
        return False
    return (
        (surface is None or base.get("surface") == surface)
        and (language is None or base.get("language") == language)
    )


def revoke_receipt(
    receipt: dict, *, path: Path | None = None, now: datetime | None = None,
) -> dict[str, Any]:
    fields = SOURCE_FIELDS if set(receipt) == SOURCE_FIELDS else CONSENT_FIELDS
    base = _receipt_base(receipt, fields)
    kind = SOURCE_KIND if fields is SOURCE_FIELDS else CONSENT_KIND
    if base is None or not attest.verify(kind, base, receipt.get("attestation")):
        raise ValueError("إيصال غير صالح للإبطال")
    base_row = {
        "schema": RECEIPT_SCHEMA,
        "receipt_id_sha256": _sha_text(str(base["receipt_id"])),
        "revoked_at_utc": _stamp(_utc(now)),
        "delete_at_utc": str(base["delete_at_utc"]),
    }
    row = _signed(REVOCATION_KIND, base_row)
    ledger = path or REVOCATION_LEDGER
    ledger.parent.mkdir(parents=True, exist_ok=True)
    descriptor = os.open(ledger, os.O_APPEND | os.O_CREAT | os.O_WRONLY, 0o600)
    with os.fdopen(descriptor, "a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")
    return row


def purge_expired_revocations(
    *, path: Path | None = None, now: datetime | None = None,
) -> int:
    ledger = path or REVOCATION_LEDGER
    if not ledger.is_file():
        return 0
    moment = _utc(now)
    kept: list[str] = []
    removed = 0
    for line in ledger.read_text(encoding="utf-8", errors="replace").splitlines():
        try:
            row = json.loads(line)
            base = {
                key: value for key, value in row.items()
                if key != "attestation"
            }
            valid = (
                isinstance(row, dict)
                and set(row) == REVOCATION_FIELDS
                and base.get("schema") == RECEIPT_SCHEMA
                and attest.verify(
                    REVOCATION_KIND, base, row.get("attestation")
                )
            )
            delete_at = _parse_stamp(base.get("delete_at_utc")) if valid else None
        except (json.JSONDecodeError, AttributeError):
            row, delete_at, valid = None, None, False
        if valid and delete_at is not None and delete_at <= moment:
            removed += 1
        else:
            # Invalid rows are deliberately retained: deleting corruption
            # would turn a fail-closed ledger into a fail-open one.
            kept.append(
                line if not valid else json.dumps(
                    row, ensure_ascii=False, separators=(",", ":")
                )
            )
    temporary = ledger.with_suffix(ledger.suffix + ".tmp")
    temporary.write_text(("\n".join(kept) + "\n") if kept else "", encoding="utf-8")
    os.replace(temporary, ledger)
    return removed


def _capsule_from_trusted_check(
    check: dict, *, surface: str, language: str = "ar",
    now: datetime | None = None, _seal: object | None = None,
) -> dict[str, Any] | None:
    """Create one HMAC-authenticated capsule, or ``None`` when unavailable.

    Partial, failed, rejected, and healthy checks honestly produce no capsule.
    A forged object claiming ``complete`` raises instead of being rounded down
    to a normal no-finding result.
    """
    if _seal is not _TRUSTED_CHECK_SEAL:
        raise RuntimeError("trusted check builder is internal")
    if surface not in SURFACES:
        raise ValueError(f"سطح غير معتمد: {surface}")
    if language not in {"ar", "en"}:
        raise ValueError("اللغة المدعومة في هذا العقد هي ar أو en")
    if not isinstance(check, dict) or check.get("status") != "complete":
        return None
    moment = _utc(now)
    problems = _closed_check(check, moment)
    if problems:
        raise ValueError("فحص مرفوض: " + " · ".join(problems))

    indexed = {
        row["key"]: row for row in check["signals"]
        if isinstance(row, dict) and row.get("key") in REMEDIES
    }
    signal_key = next(
        (key for key in REMEDIES
         if key in indexed and indexed[key].get("ok") is False
         and indexed[key].get("weight", 0) > 0),
        None,
    )
    if signal_key is None:
        return None

    checked_url = str(check["checked_url"])
    target_origin = str(check["checked_origin"])
    issued = _stamp(moment)
    expires = _stamp(moment + RECEIPT_TTL)
    target_hash = _sha_text(checked_url)
    source_base = {
        "schema": RECEIPT_SCHEMA,
        "receipt_id": "src_" + secrets.token_urlsafe(18),
        "source_token": "tok_" + secrets.token_urlsafe(18),
        "target_sha256": target_hash,
        "target_origin": target_origin,
        "measurement_sha256": _sha_json(check),
        "check_schema": CHECK_SCHEMA,
        "measurement": MEASUREMENT,
        "signal_key": signal_key,
        "result": "miss",
        "score_percent": check["score_percent"],
        "coverage_percent": check["coverage_percent"],
        "measured_at_utc": check["measured_at_utc"],
        "language": language,
        "purpose": "transient-public-page-proof",
        **SIGNED_PERMISSIONS,
        "surface": surface,
        "issued_at_utc": issued,
        "expires_at_utc": expires,
        "delete_at_utc": expires,
    }
    consent_base = {
        "schema": RECEIPT_SCHEMA,
        "receipt_id": "req_" + secrets.token_urlsafe(18),
        # This proves a request reached the tool.  It does NOT assert ownership
        # of the submitted domain and does not authorise later outreach.
        "consent_state": "request-submitted",
        "purpose": "transient-public-page-check",
        "target_sha256": target_hash,
        "target_origin": target_origin,
        "language": language,
        **SIGNED_PERMISSIONS,
        "surface": surface,
        "issued_at_utc": issued,
        "expires_at_utc": expires,
        "delete_at_utc": expires,
    }
    language_remedies = REMEDIES if language == "ar" else REMEDIES_EN
    label, imperative, acceptance = language_remedies[signal_key]
    capsule = {
        "schema": SCHEMA,
        "surface": surface,
        "language": language,
        # The full path remains covered by a hash, never exported as prose.
        "target": target_origin,
        "finding": {
            "signal_key": signal_key,
            "label": label,
            "methodology_reference": METHOD_REFS[signal_key],
        },
        "evidence": {
            "measurement": MEASUREMENT,
            "result": "miss",
            "score_percent": check["score_percent"],
            "coverage_percent": check["coverage_percent"],
            "measured_at_utc": check["measured_at_utc"],
        },
        "imperative": imperative,
        "acceptance": acceptance,
        "recheck_url": RECHECK_URL,
        "offer_url": None if surface == ISOLATED_SURFACE else OFFER_URLS[language],
        "consent_receipt": _signed(CONSENT_KIND, consent_base),
        "source_receipt": _signed(SOURCE_KIND, source_base),
        "permissions": {
            **SIGNED_PERMISSIONS,
            "delete_at_utc": expires,
        },
        "built_at_utc": issued,
        "expires_at_utc": expires,
    }
    validation = validate(capsule, surface=surface, now=moment)
    if validation:
        raise RuntimeError("الكبسولة المنتجة فشلت عقدها: " + " · ".join(validation))
    return capsule


def measure_public_page(
    url: str, *, surface: str, language: str = "ar",
    now: datetime | None = None,
) -> dict[str, Any]:
    """Run the trusted checker and, when possible, issue one proof capsule.

    This is the only production entry point.  The caller supplies a URL, not a
    measurement dictionary.  Missing signing material is a closed public
    state (``proof_status=unavailable``), never a raw exception or a capsule
    with unverifiable provenance.
    """
    if surface not in SURFACES:
        raise ValueError(f"سطح غير معتمد: {surface}")
    if language not in {"ar", "en"}:
        raise ValueError("اللغة المدعومة في هذا العقد هي ar أو en")
    moment = _utc(now)
    check = check_public_page(url)
    if not isinstance(check, dict) or check.get("status") != "complete":
        return {
            "check": check,
            "capsule": None,
            "proof_status": "not_applicable",
        }
    try:
        capsule = _capsule_from_trusted_check(
            check, surface=surface, language=language, now=moment,
            _seal=_TRUSTED_CHECK_SEAL,
        )
    except (RuntimeError, TypeError, ValueError):
        return {
            "check": check,
            "capsule": None,
            "proof_status": "unavailable",
        }
    return {
        "check": check,
        "capsule": capsule,
        "proof_status": "verified" if capsule is not None else "not_applicable",
    }


def capsule_from_check(*_args: object, **_kwargs: object) -> None:
    """Closed seam: unauthenticated caller-supplied measurements are refused."""
    raise RuntimeError(
        "capsule_from_check is closed; use measure_public_page(url, ...)"
    )


def validate(
    capsule: object, *, surface: str | None = None,
    now: datetime | None = None, revocations_path: Path | None = None,
) -> list[str]:
    """Enumerate every contract violation; an empty list is the only pass."""
    out: list[str] = []
    moment = _utc(now)
    if not isinstance(capsule, dict):
        return ["الكبسولة ليست كائناً"]
    if set(capsule) != CAPSULE_FIELDS:
        out.append("مخطط الكبسولة غير مغلق")
        return out
    cap_surface = capsule.get("surface")
    if cap_surface not in SURFACES:
        out.append("سطح الكبسولة غير معتمد")
    if surface is not None and cap_surface != surface:
        out.append("الكبسولة موثقة برمز HMAC لسطح آخر")
    if capsule.get("schema") != SCHEMA:
        out.append("مخطط الكبسولة غير معتمد")
    language = capsule.get("language")
    if language not in {"ar", "en"}:
        out.append("لغة الكبسولة غير معتمدة")
    if _origin(capsule.get("target")) != capsule.get("target"):
        out.append("الهدف ليس أصلاً عاماً منظفاً")

    finding = capsule.get("finding")
    if not isinstance(finding, dict) or set(finding) != FINDING_FIELDS:
        out.append("مخطط finding غير مغلق")
        finding = {}
    signal_key = finding.get("signal_key")
    language_remedies = REMEDIES if language == "ar" else REMEDIES_EN
    remedy = language_remedies.get(signal_key)
    if remedy is None:
        out.append("إشارة finding غير معتمدة")
    else:
        if finding.get("label") != remedy[0]:
            out.append("وصف العيب لم يصدر من العقد")
        if finding.get("methodology_reference") != METHOD_REFS[signal_key]:
            out.append("إحالة المنهجية غير مطابقة")
        if capsule.get("imperative") != remedy[1]:
            out.append("الأمر العلاجي لم يصدر من العقد")
        if capsule.get("acceptance") != remedy[2]:
            out.append("معيار القبول لم يصدر من العقد")

    evidence = capsule.get("evidence")
    if not isinstance(evidence, dict) or set(evidence) != EVIDENCE_FIELDS:
        out.append("مخطط evidence غير مغلق")
        evidence = {}
    if evidence.get("measurement") != MEASUREMENT or evidence.get("result") != "miss":
        out.append("هوية الدليل أو نتيجته غير مطابقة")
    for field in ("score_percent", "coverage_percent"):
        value = evidence.get(field)
        if type(value) is not int or not 0 <= value <= 100:
            out.append(f"{field} في الدليل غير صالح")
    measured = _parse_stamp(evidence.get("measured_at_utc"))
    if measured is None or measured > moment + timedelta(minutes=2) or moment - measured > MAX_CHECK_AGE:
        out.append("زمن الدليل غير صالح")

    if capsule.get("recheck_url") != RECHECK_URL:
        out.append("رابط إعادة الفحص غير معتمد")
    expected_offer = (
        None if cap_surface == ISOLATED_SURFACE else OFFER_URLS.get(language)
    )
    if capsule.get("offer_url") != expected_offer:
        out.append("رابط العرض يخالف عقد السطح")
    permissions = capsule.get("permissions")
    expected_permissions = {
        "scan_public_url": True,
        "display_to_requester": True,
        "store_result": False,
        "share_result": False,
        "aggregate_result": False,
        "delete_at_utc": capsule.get("expires_at_utc"),
    }
    if not isinstance(permissions, dict) or set(permissions) != PERMISSION_FIELDS or permissions != expected_permissions:
        out.append("الصلاحيات ليست عابرة وخاصة بالمستدعي")

    source = capsule.get("source_receipt")
    consent = capsule.get("consent_receipt")
    if not verify_source_receipt(
        source, surface=cap_surface, signal_key=signal_key,
        language=capsule.get("language"), now=moment,
        revocations_path=revocations_path,
    ):
        out.append("إيصال المصدر غير صالح أو منتهي أو مبطل")
    if not verify_consent_receipt(
        consent, surface=cap_surface, language=capsule.get("language"),
        now=moment,
        revocations_path=revocations_path,
    ):
        out.append("إيصال الطلب غير صالح أو منتهي أو مبطل")
    if isinstance(source, dict) and isinstance(consent, dict):
        for key in ("target_sha256", "target_origin", "surface", "language",
                    "issued_at_utc", "expires_at_utc", "delete_at_utc"):
            if source.get(key) != consent.get(key):
                out.append(f"الإيصالان يختلفان في {key}")
        if source.get("target_origin") != capsule.get("target"):
            out.append("الهدف لا يطابق إيصال المصدر")
        if source.get("measurement") != evidence.get("measurement"):
            out.append("نوع القياس لا يطابق إيصال المصدر")
        if source.get("measured_at_utc") != evidence.get("measured_at_utc"):
            out.append("زمن القياس لا يطابق إيصال المصدر")
        if source.get("score_percent") != evidence.get("score_percent") or source.get("coverage_percent") != evidence.get("coverage_percent"):
            out.append("أرقام الدليل لا تطابق إيصال المصدر")
        for key, value in SIGNED_PERMISSIONS.items():
            if source.get(key) is not value or consent.get(key) is not value:
                out.append(f"الصلاحية الموثقة برمز HMAC {key} غير مطابقة")

    built = _parse_stamp(capsule.get("built_at_utc"))
    expires = _parse_stamp(capsule.get("expires_at_utc"))
    if built is None or expires is None or built > moment + timedelta(minutes=2) or not built < expires or moment >= expires:
        out.append("نافذة صلاحية الكبسولة غير صالحة")
    elif expires - built > RECEIPT_TTL:
        out.append("صلاحية الكبسولة أطول من العقد")
    if isinstance(source, dict) and (
            capsule.get("built_at_utc") != source.get("issued_at_utc")
            or capsule.get("expires_at_utc") != source.get("expires_at_utc")):
        out.append("صلاحية الكبسولة لا تطابق إيصالها")

    for name in ("imperative", "acceptance"):
        if not _safe_human(capsule.get(name)):
            out.append(f"{name} غير آمن للعرض")
    if isinstance(finding, dict) and not _safe_human(finding.get("label")):
        out.append("label غير آمن للعرض")
    return out


def present(
    capsule: dict, surface: str, now: datetime | None = None,
) -> str:
    """Render only after revalidation, with commerce isolated by surface."""
    problems = validate(capsule, surface=surface, now=now)
    if problems:
        raise ValueError("كبسولة غير قابلة للعرض: " + " · ".join(problems))
    finding = capsule["finding"]
    evidence = capsule["evidence"]
    if capsule["language"] == "en":
        lines = [
            f"One measured finding for {capsule['target']}",
            finding["label"],
            (f"The check completed with {evidence['coverage_percent']}% coverage "
             f"and a page-basics score of {evidence['score_percent']}%."),
            f"Action: {capsule['imperative']}",
            f"Acceptance: {capsule['acceptance']}",
            "Limit: this checks public-page basics; it does not measure rankings or sales.",
        ]
        if surface != ISOLATED_SURFACE:
            lines.extend((
                f"Recheck: {RECHECK_URL}",
                f"Full audit: {capsule['offer_url']}",
            ))
    else:
        lines = [
            f"ملاحظة واحدة مقيسة على {capsule['target']}",
            finding["label"],
            (f"الفحص مكتمل بتغطية {evidence['coverage_percent']}%، "
             f"ودرجة أساسيات الصفحة {evidence['score_percent']}%."),
            f"الإجراء: {capsule['imperative']}",
            f"معيار القبول: {capsule['acceptance']}",
            "الحد: هذا فحص لأساسيات صفحة عامة؛ لا يقيس الترتيب أو المبيعات.",
        ]
        if surface != ISOLATED_SURFACE:
            lines.extend((
                f"إعادة الفحص: {RECHECK_URL}",
                f"التدقيق الكامل متاح هنا: {capsule['offer_url']}",
            ))
    return "\n".join(lines)


def verify_recheck_request(
    url: str, source_receipt: dict, now: datetime | None = None,
    *, language: str,
) -> bool:
    """A recheck may run only for the HMAC-bound path and response language."""
    return verify_source_receipt(
        source_receipt, target_url=url, language=language, now=now,
    )


def _fixture(now: datetime, *, miss: str | None = "title") -> dict[str, Any]:
    signals = []
    for key in SIGNAL_WEIGHT_CONTRACT:
        if key == "jsonld_valid":
            continue
        ok = key != miss
        signals.append({
            "key": key,
            "ok": ok,
            "detail": f"fixed {key} detail",
            "weight": SIGNAL_WEIGHT_CONTRACT[key],
            "evidence": "",
        })
    total = sum(row["weight"] for row in signals)
    got = sum(row["weight"] for row in signals if row["ok"])
    score = round(100 * got / total) if total else 0
    weighted_misses = sum(
        1 for row in signals if not row["ok"] and row["weight"] > 0
    )
    row = {
        "schema": CHECK_SCHEMA,
        "execution_ok": True,
        "readiness_passed": score == 100 and weighted_misses == 0,
        "ok": True,
        "status": "complete",
        "measurement": MEASUREMENT,
        "checked_url": "https://merchant.example/products",
        "checked_origin": "https://merchant.example/",
        "score_percent": score,
        "coverage_percent": 100,
        "signals": signals,
        "weighted_miss_count": weighted_misses,
        "note_miss_count": sum(
            1 for item in signals if not item["ok"] and item["weight"] == 0
        ),
        "unchecked_count": 0,
        "errors": [],
        "selected_transport_limits": {
            "timeout_seconds": 10,
            "max_url_chars": 2048,
            "max_body_bytes": 1000000,
            "max_redirects": 5,
            "max_html_bytes": 500000,
            "max_html_fact_bytes": 100000,
            "html_parse_timeout_seconds": 2.0,
        },
        "scope": SCOPE,
        "not_measured": list(NOT_MEASURED),
        "measured_at_utc": _stamp(now),
    }
    return {key: row[key] for key in CHECK_KEYS}


def selftest() -> int:
    import copy
    import tempfile
    from unittest import mock

    prior = os.environ.get(attest.ENV_NAME)
    test_secret = "proof-capsule-selftest-key-0123456789abcdef"
    os.environ[attest.ENV_NAME] = test_secret

    class _SelftestKey:
        key_id = "proof-capsule-selftest"
        env_name = attest.ENV_NAME
        secret_field = attest.SECRET_FIELD
        usage = "sign_and_verify"
        material = test_secret.encode("utf-8")

    class _SelftestKeyring:
        policy_version = "2026-08-27.1"
        active_signing_key_id = _SelftestKey.key_id
        accepted_verification_key_ids = (_SelftestKey.key_id,)
        accepted_attestation_policy_versions = (policy_version,)
        keys = (_SelftestKey(),)

        def active_key(self):
            return self.keys[0]

        def key_by_id(self, key_id: str):
            return self.keys[0] if key_id == self.keys[0].key_id else None

    keyring_patch = mock.patch.object(
        attest, "_resolved_keyring", return_value=_SelftestKeyring())
    keyring_patch.start()
    now = _utc()
    failures: list[str] = []
    try:
        check = _fixture(now)
        with mock.patch.object(
                sys.modules[__name__], "check_public_page",
                return_value=check):
            measured = measure_public_page(
                "https://merchant.example/products",
                surface=ISOLATED_SURFACE, now=now,
            )
        capsule = measured["capsule"]
        if measured["proof_status"] != "verified":
            failures.append("مسار القياس الموثوق لم يصدر proof_status=verified")
        if capsule is None or validate(capsule, surface=ISOLATED_SURFACE, now=now):
            failures.append("العقد الكامل لم ينتج كبسولة صالحة")
        if capsule:
            rendered = present(capsule, ISOLATED_SURFACE, now=now)
            if OFFER_URL in rendered or "التدقيق الكامل" in rendered:
                failures.append("السطح المعزول سرّب عرضاً تجارياً")
            if not verify_recheck_request(
                    "https://merchant.example/products?secret=x",
                    capsule["source_receipt"], now=now, language="ar"):
                failures.append("إعادة الفحص المطابقة رُفضت")
            if verify_recheck_request(
                    "https://merchant.example/other",
                    capsule["source_receipt"], now=now, language="ar"):
                failures.append("إعادة فحص لهدف آخر قُبلت")
            if verify_recheck_request(
                    "https://merchant.example/products",
                    capsule["source_receipt"], now=now, language="en"):
                failures.append("إعادة فحص بلغة غير موثقة برمز HMAC قُبلت")
            tampered = copy.deepcopy(capsule)
            tampered["evidence"]["score_percent"] = 100
            if not validate(tampered, surface=ISOLATED_SURFACE, now=now):
                failures.append("تغيير الدليل لم يُرصد")
            extra = copy.deepcopy(capsule)
            extra["trusted"] = True
            if not validate(extra, surface=ISOLATED_SURFACE, now=now):
                failures.append("حقل زائد لم يُرصد")
            forged = copy.deepcopy(capsule)
            forged["source_receipt"]["signal_key"] = "description"
            if not validate(forged, surface=ISOLATED_SURFACE, now=now):
                failures.append("تزوير إيصال المصدر لم يُرصد")
            with tempfile.TemporaryDirectory() as folder:
                ledger = Path(folder) / "revoked.jsonl"
                revoke_receipt(capsule["source_receipt"], path=ledger, now=now)
                if verify_source_receipt(
                        capsule["source_receipt"], now=now,
                        revocations_path=ledger):
                    failures.append("إيصال مبطل ظل صالحاً")
                if purge_expired_revocations(
                        path=ledger, now=now + RECEIPT_TTL) != 1:
                    failures.append("حذف سجل الإبطال المنتهي لم يعمل")
                ledger.write_text('{"corrupted":true}\n', encoding="utf-8")
                if not receipt_revoked(
                        capsule["source_receipt"]["receipt_id"], ledger):
                    failures.append("فساد سجل الإبطال فتح الإيصال")
        healthy = _fixture(now, miss=None)
        with mock.patch.object(
                sys.modules[__name__], "check_public_page",
                return_value=healthy):
            healthy_result = measure_public_page(
                "https://merchant.example/products",
                surface="mcp-registry", now=now,
            )
        if healthy_result["capsule"] is not None:
            failures.append("فحص سليم اخترع عيباً")
        partial = _fixture(now)
        partial["status"] = "partial"
        partial["ok"] = False
        with mock.patch.object(
                sys.modules[__name__], "check_public_page",
                return_value=partial):
            partial_result = measure_public_page(
                "https://merchant.example/products",
                surface="mcp-registry", now=now,
            )
        if partial_result["capsule"] is not None:
            failures.append("فحص جزئي أنتج كبسولة")
        forged_check = _fixture(now)
        forged_check["score_percent"] = 100
        with mock.patch.object(
                sys.modules[__name__], "check_public_page",
                return_value=forged_check):
            forged_result = measure_public_page(
                "https://merchant.example/products",
                surface="mcp-registry", now=now,
            )
        if forged_result["proof_status"] != "unavailable" or forged_result["capsule"] is not None:
            failures.append("فحص كامل متناقض لم يُغلق كـ unavailable")
        try:
            capsule_from_check(
                check, surface="mcp-registry", now=now,
            )
            failures.append("واجهة dict القديمة بقيت مفتوحة")
        except RuntimeError:
            pass
        with mock.patch.object(
                attest, "sign", side_effect=RuntimeError("missing key")), \
                mock.patch.object(
                    sys.modules[__name__], "check_public_page",
                    return_value=check):
            no_key = measure_public_page(
                "https://merchant.example/products",
                surface="mcp-registry", now=now,
            )
        if no_key["proof_status"] != "unavailable" or no_key["capsule"] is not None:
            failures.append("غياب مفتاح التوقيع لم يُترجم إلى unavailable")
    finally:
        keyring_patch.stop()
        if prior is None:
            os.environ.pop(attest.ENV_NAME, None)
        else:
            os.environ[attest.ENV_NAME] = prior
    if failures:
        print("SELFTEST FAIL")
        for failure in failures:
            print(" -", failure)
        return 1
    print("SELFTEST PASS: closed check, HMAC-authenticated receipts, revocation, exact recheck, isolated commerce")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="كبسولة برهان عابرة موثقة برمز HMAC")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args(argv)
    if not args.selftest:
        parser.error("--selftest مطلوب؛ الإنتاج يمر من خادم الأداة فقط")
    return selftest()


if __name__ == "__main__":
    raise SystemExit(main())
