# Generated from the maintained Advisors AI server sources.
# Report issues in this repository; do not edit this file directly.
# -*- coding: utf-8 -*-
"""Non-HTTP projection of the ``advisorsai-check`` core.

Returns one fixed JSON contract for declared public-page machine basics.
This module does not open an HTTP listener and does not render a UI.

Authority for score/coverage/success is the core ``Report`` only.  The
wrapper sanitises projection fields and never invents a second scorer.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

from advisorsai_check.core import (
    HTML_PARSE_TIMEOUT,
    MAX_BODY_BYTES,
    MAX_HTML_BYTES,
    MAX_HTML_FACT_BYTES,
    MAX_REDIRECTS,
    MAX_URL_CHARS,
    REQUIRED_SIGNAL_KEYS,
    SIGNAL_WEIGHT_CONTRACT,
    TIMEOUT,
    Report,
    Signal,
    UnsafeTarget,
    normalise,
    run as checker_run,
)

SCHEMA = "almanzoma.public_readiness_check/v2"
MEASUREMENT = "declared_public_page_machine_basics"
SCOPE = (
    "declared robots policy for the submitted path plus retrievable page "
    "and discovery-file basics"
)
NOT_MEASURED = (
    "ten-axis store or site audit",
    "whether an AI assistant mentions the business",
    "AI answer visibility, ranking, or share",
    "sales or conversion probability",
)
# Remote title/heading/description text must not enter the JSON contract.
_FIXED_DETAIL_KEYS = frozenset({"title", "description", "h1"})
_OSC = re.compile(r"\x1b\].*?(?:\x07|\x1b\\|$)", re.S)
_CSI = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")
_ESCAPE = re.compile(r"\x1b(?:[ -/]*[@-~])?")
_HTML_MARK = re.compile(r"[<>]|</|\b(?:script|iframe|object|embed)\b", re.I)
_PATH_EVIDENCE = re.compile(r"^/[A-Za-z0-9._~\-/]{1,128}\Z")
_SAFE_CHECKED = re.compile(
    r"^https?://[A-Za-z0-9._~\-]+(?::\d{1,5})?(?:/[A-Za-z0-9._~\-/]*)?$"
)

CONTRACT_KEYS = (
    "schema",
    "execution_ok",
    "readiness_passed",
    "ok",
    "status",
    "measurement",
    "checked_url",
    "checked_origin",
    "score_percent",
    "coverage_percent",
    "signals",
    "weighted_miss_count",
    "note_miss_count",
    "unchecked_count",
    "errors",
    "selected_transport_limits",
    "scope",
    "not_measured",
    "measured_at_utc",
)


def _safe_text(value: object) -> str:
    cleaned = _OSC.sub("", str(value))
    cleaned = _CSI.sub("", cleaned)
    cleaned = _ESCAPE.sub("", cleaned)
    cleaned = "".join(
        " " if character in "\r\n\t" else character
        for character in cleaned
        if character in "\r\n\t"
        or unicodedata.category(character) not in {"Cc", "Cf", "Cs"}
    )
    return re.sub(r"\s+", " ", cleaned).strip()


def _origin_only(url: str) -> str:
    """Origin of an ALREADY-SANITISED url. Never fed the raw one.

    Two defects lived here until 2026-08-22, both measured:

    1. `checked_origin` was derived from `report.url` while `checked_url`
       came from the sanitised text, so the two fields naming one origin
       DISAGREED — and the unsanitised one carried exactly what the
       sanitiser exists to strip: `https://exa\x1b\x07mple.com/` beside a
       clean `https://example.com/path`, and a zero-width space that
       reached the JSON literally (`ensure_ascii=False`), which is a
       host-spoofing surface: two different names rendering identically.
    2. `urlsplit` RAISES on some inputs (`ValueError: Invalid IPv6 URL`),
       and `project_report` sits outside any `try` — so the module's first
       documented promise, "one fixed JSON contract", became a bare
       traceback.

    Both are closed by construction now: the caller passes the sanitised
    url, and a parse failure returns "" instead of escaping upward.
    """
    try:
        parsed = urlsplit(url)
    except ValueError:
        return ""
    if not parsed.scheme or not parsed.netloc:
        return ""
    return urlunsplit((parsed.scheme, parsed.netloc, "/", "", ""))


def _safe_checked_url(url: str) -> str | None:
    """Return scheme+host+path only; drop query, fragment, userinfo, markup."""
    text = _safe_text(url)
    if not text:
        return None
    parsed = urlsplit(text)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        return None
    if "@" in parsed.netloc:
        return None
    path = parsed.path or "/"
    if ".." in path.split("/") or _HTML_MARK.search(path):
        return None
    host = parsed.netloc.lower()
    if _HTML_MARK.search(host):
        return None
    candidate = urlunsplit((parsed.scheme, host, path, "", ""))
    if not _SAFE_CHECKED.fullmatch(candidate):
        return _origin_only(candidate)
    return candidate


def _fixed_detail(key: str, ok: bool | None) -> str:
    if key == "title":
        if ok is True:
            return "a sufficiently descriptive page title is present"
        if ok is False:
            return "the submitted page lacks a sufficiently descriptive title"
        return "the page title could not be evaluated"
    if key == "description":
        if ok is True:
            return "a meta description is present"
        if ok is False:
            return "the submitted page lacks a usable meta description"
        return "the meta description could not be evaluated"
    if key == "h1":
        if ok is True:
            return "exactly one primary heading is present"
        if ok is False:
            return (
                "the submitted page does not have exactly one primary heading"
            )
        return "the primary heading could not be evaluated"
    return "signal detail unavailable"


def _robots_detail(signal: Signal) -> str:
    """Keep core's closed reason; never invent allow/deny from ok alone."""
    text = _safe_text(signal.detail)
    if not text or _HTML_MARK.search(text):
        if signal.ok is True:
            return "robots policy signal returned ok without a usable detail"
        if signal.ok is False:
            return "robots policy signal returned miss without a usable detail"
        return "robots policy signal could not be evaluated"
    # Strip query-like attacker surface from path echoes in core detail.
    text = re.sub(r"\?[^\s]*", "", text)
    return text[:300]


def _safe_evidence(value: object) -> str:
    text = _safe_text(value)
    if not text or _HTML_MARK.search(text):
        return ""
    if _PATH_EVIDENCE.fullmatch(text):
        return text
    return ""


def _project_signal(signal: Signal) -> dict[str, Any]:
    key = _safe_text(signal.key)
    ok = signal.ok
    if key == "robots":
        detail = _robots_detail(signal)
    elif key in _FIXED_DETAIL_KEYS:
        detail = _fixed_detail(key, ok)
    else:
        detail = _safe_text(signal.detail)
        if _HTML_MARK.search(detail):
            detail = "signal detail redacted"
    return {
        "key": key,
        "ok": ok,
        "detail": detail,
        "weight": int(signal.weight),
        "evidence": _safe_evidence(signal.evidence),
    }


def _selected_transport_limits() -> dict[str, float | int]:
    return {
        "timeout_seconds": int(TIMEOUT),
        "max_url_chars": int(MAX_URL_CHARS),
        "max_body_bytes": int(MAX_BODY_BYTES),
        "max_redirects": int(MAX_REDIRECTS),
        "max_html_bytes": int(MAX_HTML_BYTES),
        "max_html_fact_bytes": int(MAX_HTML_FACT_BYTES),
        "html_parse_timeout_seconds": float(HTML_PARSE_TIMEOUT),
    }


def _classify_unsafe(exc: UnsafeTarget, url: str = "") -> tuple[str, str]:
    """Map core UnsafeTarget text to stable error tokens (no invention).

    The URL matters, not just the message. Measured against the real core
    2026-08-22: it answers `ftp://`, `gopher://`, `file://`, `localhost`,
    `127.0.0.1` and `2130706433` with the SAME sentence — "not a public site
    address". Reading the message alone therefore told a client who pasted
    an `ftp://` link that their target was "private or mixed", which is
    simply untrue, and left `scheme_not_web` unreachable. The scheme is
    already in our hand, so we read it instead of guessing from prose.

    Ordering also matters: `"port" in msg` matches inside "sup-port-ed",
    and the core's own port sentence ends with "are supported". Any future
    scheme sentence carrying that word would have been reported as a port
    problem, so the port test now needs a whole word and comes last.
    """
    msg = str(exc).lower()
    scheme = ""
    try:
        scheme = urlsplit(_safe_text(url)).scheme.lower()
    except ValueError:
        scheme = ""
    if scheme and scheme not in {"http", "https"}:
        return "target_rejected", "scheme_not_web"
    if "could not be resolved" in msg:
        return "check_unavailable", "dns_unresolved"
    if "credential" in msg:
        return "target_rejected", "credentials_forbidden"
    if "only http" in msg or "scheme" in msg:
        return "target_rejected", "scheme_not_web"
    if (
        "private" in msg or "mixed" in msg or "local" in msg
        or "reserved" in msg or "not a public" in msg
    ):
        return "target_rejected", "blocked_private_or_mixed"
    # `ports?` لا `port`: رسالةُ النواة الحقيقية جمعٌ — «only standard web
    # **ports** 80 and 443 are supported». وحدُّ الكلمة المفرد أسقطها إلى
    # `unsafe_target` — انحدارٌ أحدثه إصلاحي نفسه، أمسكه القياس لا القراءة.
    if re.search(r"\bports?\b", msg):
        return "target_rejected", "non_standard_port"
    if "too long" in msg:
        return "target_rejected", "url_too_long"
    if "required" in msg or "malformed" in msg:
        return "target_rejected", "unusable_or_non_public"
    return "target_rejected", "unsafe_target"


def _empty_result(
        *,
        status: str,
        errors: list[str] | None = None,
        execution_ok: bool = True,
) -> dict[str, Any]:
    return {
        "schema": SCHEMA,
        "execution_ok": execution_ok,
        "readiness_passed": False,
        "ok": False,
        "status": status,
        "measurement": None,
        "checked_url": None,
        "checked_origin": None,
        "score_percent": None,
        "coverage_percent": None,
        "signals": [],
        "weighted_miss_count": None,
        "note_miss_count": None,
        "unchecked_count": None,
        "errors": list(errors or []),
        "selected_transport_limits": _selected_transport_limits(),
        "scope": None,
        "not_measured": list(NOT_MEASURED),
        "measured_at_utc": (
            datetime.now(UTC).replace(microsecond=0).isoformat()
        ),
    }


def check_public_page(url: str) -> dict[str, Any]:
    """Return the fixed public-page-basics JSON contract for ``url``."""
    if not isinstance(url, str) or not url.strip():
        return _empty_result(
            status="target_rejected",
            errors=["url_required"],
        )
    if len(url) > MAX_URL_CHARS:
        return _empty_result(
            status="target_rejected",
            errors=["url_too_long"],
        )
    try:
        normalised = normalise(url)
    except UnsafeTarget as exc:
        status, code = _classify_unsafe(exc, url)
        return _empty_result(status=status, errors=[code])
    except (TypeError, ValueError):
        return _empty_result(
            status="target_rejected",
            errors=["unusable_target"],
        )

    try:
        report = checker_run(normalised)
    except UnsafeTarget as exc:
        status, code = _classify_unsafe(exc, url)
        return _empty_result(status=status, errors=[code])
    except TimeoutError:
        return _empty_result(
            status="check_unavailable",
            errors=["timeout"],
            execution_ok=False,
        )
    except Exception as exc:  # noqa: BLE001
        return _empty_result(
            status="check_unavailable",
            errors=[type(exc).__name__],
            execution_ok=False,
        )

    return project_report(report)


def project_report(report: Report) -> dict[str, Any]:
    """Project a core ``Report``; score/coverage/success come from Report."""
    if not isinstance(report, Report):
        return _empty_result(
            status="check_unavailable",
            errors=["invalid_report"],
            execution_ok=False,
        )

    if not report.successful and report.score is None:
        # Incomplete contract or errors: still project when signals exist,
        # but never invent a score.  Core already sets score=None.
        pass

    signals = [_project_signal(signal) for signal in report.signals]
    for item in signals:
        key = item["key"]
        if (
            key not in SIGNAL_WEIGHT_CONTRACT
            or item["weight"] != SIGNAL_WEIGHT_CONTRACT[key]
        ):
            return _empty_result(
                status="check_unavailable",
                errors=["signal_weight_mismatch"],
                execution_ok=False,
            )
    present = {item["key"] for item in signals}
    if not REQUIRED_SIGNAL_KEYS <= present:
        return _empty_result(
            status="check_unavailable",
            errors=["missing_required_signals"],
            execution_ok=False,
        )

    weighted_misses = [
        item for item in signals
        if item["ok"] is False and item["weight"] > 0
    ]
    note_misses = [
        item for item in signals
        if item["ok"] is False and item["weight"] == 0
    ]
    unchecked = [item for item in signals if item["ok"] is None]
    complete = bool(report.successful)
    status = "complete" if complete else "partial"
    # Core authority — do not recompute ratios.
    score_percent = report.score
    coverage_percent = report.coverage_percent
    readiness_passed = bool(
        complete
        and score_percent is not None
        and score_percent == 100
        and not weighted_misses
    )
    errors = [_safe_text(err) for err in report.errors]
    errors = [err for err in errors if err and not _HTML_MARK.search(err)]
    checked = _safe_checked_url(report.url)

    payload = {
        "schema": SCHEMA,
        "execution_ok": True,
        "readiness_passed": readiness_passed,
        # ok = measurement completed (all required signals evaluated), not 100%.
        "ok": complete,
        "status": status,
        "measurement": MEASUREMENT,
        "checked_url": checked,
        # من `checked` المعقَّم لا من `report.url` الخام — وإلا اختلف
        # الحقلان وحمل أحدهما ما وُجد المعقّم ليزيله.
        "checked_origin": (_origin_only(checked) or None) if checked else None,
        "score_percent": score_percent,
        "coverage_percent": coverage_percent,
        "signals": signals,
        "weighted_miss_count": len(weighted_misses),
        "note_miss_count": len(note_misses),
        "unchecked_count": len(unchecked),
        "errors": errors,
        "selected_transport_limits": _selected_transport_limits(),
        "scope": SCOPE,
        "not_measured": list(NOT_MEASURED),
        "measured_at_utc": (
            datetime.now(UTC).replace(microsecond=0).isoformat()
        ),
    }
    if tuple(payload.keys()) != CONTRACT_KEYS:
        raise RuntimeError("public readiness contract key order broken")
    return payload


def dumps_contract(payload: dict[str, Any]) -> str:
    if tuple(payload.keys()) != CONTRACT_KEYS:
        raise RuntimeError("public readiness contract key order broken")
    return json.dumps(
        payload,
        ensure_ascii=False,
        allow_nan=False,
        separators=(",", ":"),
    )


def selftest() -> None:
    rejected = check_public_page("http://127.0.0.1/")
    assert rejected["status"] == "target_rejected", rejected
    assert rejected["execution_ok"] is True
    assert rejected["readiness_passed"] is False
    assert rejected["errors"] == ["blocked_private_or_mixed"]
    assert tuple(rejected.keys()) == CONTRACT_KEYS
    assert "selected_transport_limits" in rejected
    assert "max_redirects" in rejected["selected_transport_limits"]

    for bad in (
        "file:///etc/passwd",
        "https://user:secret@example.com/",
        "http://localhost/",
        "http://[::1]/",
        "http://example.com:8080/",
        "http://2130706433/",
        "",
        "x" * (MAX_URL_CHARS + 1),
    ):
        row = check_public_page(bad)
        assert row["status"] in {"target_rejected", "check_unavailable"}, (bad, row)
        assert row["readiness_passed"] is False
        blob = dumps_contract(row)
        assert "<html" not in blob.lower()
        assert "</" not in blob

    # ── حارسا انحدار للعطلين المُصلَحين 2026-08-22 ─────────────────────
    # ح-أ: كل رفضٍ يُبلَّغ برمزه الصحيح. الحكم على **الرمز** لا على الحالة
    # وحدها — فالاختبار الذي يوكّد الحالة فقط هو ما أخفى العطل شهراً.
    for bad_url, want in (
            ("ftp://example.com/", "scheme_not_web"),
            ("gopher://example.com/", "scheme_not_web"),
            ("file:///etc/passwd", "scheme_not_web"),
            ("http://127.0.0.1/", "blocked_private_or_mixed"),
            ("http://localhost/", "blocked_private_or_mixed"),
            ("http://2130706433/", "blocked_private_or_mixed"),
            ("http://example.com:8080/", "non_standard_port"),
            ("https://user:secret@example.com/", "credentials_forbidden"),
            ("x" * (MAX_URL_CHARS + 1), "url_too_long"),
    ):
        got = check_public_page(bad_url)["errors"]
        assert got == [want], (bad_url, got, want)

    # ح-ب: الحقلان يسمّيان أصلاً واحداً، ولا يحمل أحدهما ما يزيله المعقّم.
    _clean = Report(
        url="https://example.com/path",
        signals=[Signal(k, True, f"{k} ok", w, "")
                 for k, w in SIGNAL_WEIGHT_CONTRACT.items()],
        errors=[],
    )
    for dirty in ("https://exa\x1b\x07mple.com/path",
                  "https://exam\u200bple.com/p",
                  "https://exa\x1b[31mmple.com/path",
                  "https://EXAMPLE.com/x"):
        row = project_report(Report(url=dirty, signals=list(_clean.signals),
                                    errors=[]))
        origin, checked = row["checked_origin"], row["checked_url"]
        assert origin and checked, (dirty, row)
        assert checked.startswith(origin.rstrip("/")), (dirty, checked, origin)
        blob = dumps_contract(row)
        assert "\u200b" not in blob, dirty
        assert not any(ord(c) < 0x20 for c in (origin + checked)), dirty

    fake = Report(
        url="https://example.com/path?x=<script>",
        signals=[
            Signal("home", True, "home page fetched", 0, ""),
            Signal("title", True, "page title: <script>x</script>", 1, "<b>x</b>"),
            Signal("description", True, "meta description, 20 chars", 1, ""),
            Signal(
                "structured_business", True,
                "Organization structured data names the business", 2, "",
            ),
            Signal(
                "structured_offering", True,
                "Service/Product structured data names an offering", 2, "",
            ),
            Signal("h1", True, "one <h1>: «Hello»", 1, ""),
            Signal(
                "canonical", True,
                "canonical link with an HTTP(S) href is present", 1, "",
            ),
            Signal(
                "robots", True,
                "robots.txt is unavailable (HTTP 404); RFC crawler policy "
                "treats it as no declared restrictions",
                2, "",
            ),
            Signal("llms_txt", False, "no /llms.txt", 0, ""),
            Signal(
                "sitemap", True,
                "valid urlset sitemap with locations", 1, "/sitemap.xml",
            ),
        ],
        errors=[],
    )
    projected = project_report(fake)
    assert projected["status"] == "complete"
    assert projected["ok"] is True
    assert projected["execution_ok"] is True
    assert projected["score_percent"] == fake.score
    assert projected["coverage_percent"] == fake.coverage_percent
    assert projected["checked_url"] == "https://example.com/path"
    assert "?" not in (projected["checked_url"] or "")
    assert "<" not in (projected["checked_url"] or "")
    robots = next(s for s in projected["signals"] if s["key"] == "robots")
    assert "404" in robots["detail"]
    assert "unavailable" in robots["detail"]
    assert "permits the scored" not in robots["detail"]
    assert projected["note_miss_count"] == 1  # llms_txt
    assert projected["weighted_miss_count"] == 0
    # score 100 with only note miss → readiness_passed
    assert projected["readiness_passed"] is True
    assert projected["selected_transport_limits"]["max_html_bytes"] == MAX_HTML_BYTES
    encoded = dumps_contract(projected)
    assert "<script" not in encoded.lower()
    print("public_readiness_check selftest: PASS")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Internal JSON contract for declared public-page machine basics "
            "(no HTTP server, no UI)."
        ),
    )
    parser.add_argument("--selftest", action="store_true")
    parser.add_argument(
        "url",
        nargs="?",
        help="Public HTTP(S) URL to check (optional when --selftest).",
    )
    args = parser.parse_args(argv)
    if args.selftest:
        selftest()
        return 0
    if not args.url:
        parser.error("url is required unless --selftest")
    payload = check_public_page(args.url)
    sys.stdout.write(dumps_contract(payload) + "\n")
    # Exit: 2 rejected · 1 incomplete execution · 0 measurement finished
    # (score may be 0). readiness_passed is a field, not the exit bit.
    if payload["status"] == "target_rejected":
        return 2
    if not payload["execution_ok"] or payload["status"] != "complete":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
