# Generated from the maintained Advisors AI server sources.
# Report issues in this repository; do not edit this file directly.
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The block that closes the miss — generated, paste-ready, never echoed back.

Measured 2026-08-24: the live tool returns ``imperative`` ("declare an
Organization node") and ``acceptance`` ("re-measure, the signal turns"), and no
remedy at all.  So we name the gap and hand the client the work — a report
wearing a tool's clothes.  ``docs/مبدأ-الإصلاح-لا-التقرير.md`` requires the
artifact that closes the miss, not a description of it.

Two rules constrain what may be generated, and both come from measurement:

1. **Never echo the fetched page back.**  This tool's output lands inside an
   assistant's context, and the page we fetched is attacker-controlled input.
   Copying its ``<title>`` into our reply is a prompt-injection carrier wearing
   a helpful hat.  So blocks carry explicit placeholders the client fills, and
   the only page-derived value ever emitted is the **origin the caller
   themselves supplied**.

2. **No remedy where a paste-ready artifact cannot close it.**  A sitemap needs
   a crawl we deliberately do not run, so we emit nothing for it and say why.
   A fabricated remedy is worse than an honest gap: it reads as closed.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from urllib.parse import urlsplit

def _origin(url: str) -> str:
    """أصلُ العنوان الذي سلّمه المتّصلُ نفسُه — لا شيءَ من جسد الصفحة."""
    parts = urlsplit(url or "")
    if parts.scheme not in {"http", "https"} or not parts.hostname:
        raise ValueError("العلاجُ لا يُبنى إلا على أصل HTTP(S) سلّمه المتّصل")
    host = parts.hostname
    if not re.fullmatch(r"[A-Za-z0-9.\-]{1,253}", host):
        raise ValueError(f"مضيفٌ غيرُ صالحٍ للبناء عليه: {host!r}")
    port = f":{parts.port}" if parts.port else ""
    return f"{parts.scheme}://{host}{port}"


COPY = {
    "en": {
        "business_name": "YOUR BUSINESS NAME",
        "business_description": "ONE SENTENCE DESCRIBING WHAT YOU DO",
        "offering_name": "WHAT YOU SELL",
        "offering_description": "ONE SENTENCE DESCRIBING THE OFFERING",
        "page_path": "THIS-PAGE-PATH",
        "page_description": (
            "ONE SENTENCE, 80-160 CHARACTERS, DESCRIBING THIS PAGE"
        ),
        "head": "inside <head>, anywhere before </head>",
        "after_org": "inside <head>, after the Organization block",
        "inside_head": "inside <head>",
        "pages_heading": "Pages",
        "home_label": "Home",
    },
    "ar": {
        "business_name": "اسم نشاطك التجاري",
        "business_description": "جملة واحدة تصف ما تقدمه",
        "offering_name": "ما تبيعه",
        "offering_description": "جملة واحدة تصف العرض",
        "page_path": "مسار-هذه-الصفحة",
        "page_description": "جملة من 80 إلى 160 محرفاً تصف هذه الصفحة",
        "head": "داخل <head> في أي موضع قبل </head>",
        "after_org": "داخل <head> بعد كتلة Organization",
        "inside_head": "داخل <head>",
        "pages_heading": "الصفحات",
        "home_label": "الرئيسية",
    },
}


def _copy(language: str) -> dict[str, str]:
    try:
        return COPY[language]
    except KeyError as exc:
        raise ValueError(f"لغةُ العلاج غيرُ مدعومة: {language!r}") from exc


def _org_block(origin: str, text: dict[str, str]) -> str:
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "Organization",
        "@id": f"{origin}/#organization",
        "name": text["business_name"],
        "url": f"{origin}/",
        "description": text["business_description"],
    }, indent=2, ensure_ascii=False)


def _offer_block(origin: str, text: dict[str, str]) -> str:
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "Service",
        "name": text["offering_name"],
        "provider": {"@id": f"{origin}/#organization"},
        "url": f"{origin}/",
        "description": text["offering_description"],
    }, indent=2, ensure_ascii=False)


def _wrap_ld(body: str) -> str:
    return f'<script type="application/ld+json">\n{body}\n</script>'


def remedy_for(signal_key: str, url: str, language: str = "en") -> dict | None:
    """يرجع العلاجَ الجاهزَ للّصق، أو None حين لا يُغلق العطلَ نصٌّ يُلصق."""
    origin = _origin(url)
    text = _copy(language)
    if signal_key == "structured_business":
        return {
            "closes": signal_key,
            "format": "html-head-block",
            "where": text["head"],
            "code": _wrap_ld(_org_block(origin, text)),
            "fill_in": [text["business_name"],
                        text["business_description"]],
        }
    if signal_key == "structured_offering":
        return {
            "closes": signal_key,
            "format": "html-head-block",
            "where": text["after_org"],
            "code": _wrap_ld(_offer_block(origin, text)),
            "fill_in": [text["offering_name"],
                        text["offering_description"]],
        }
    if signal_key == "canonical":
        return {
            "closes": signal_key,
            "format": "html-head-block",
            "where": text["inside_head"],
            "code": ('<link rel="canonical" href="'
                     f'{origin}/{text["page_path"]}">'),
            "fill_in": [text["page_path"]],
        }
    if signal_key == "description":
        return {
            "closes": signal_key,
            "format": "html-head-block",
            "where": text["inside_head"],
            "code": ('<meta name="description" content="'
                     f'{text["page_description"]}">'),
            "fill_in": [text["page_description"]],
        }
    if signal_key == "llms_txt":
        return {
            "closes": signal_key,
            "format": "new-file",
            "where": f"{origin}/llms.txt",
            "code": (f'# {text["business_name"]}\n\n'
                     f'> {text["business_description"]}\n\n'
                     f'## {text["pages_heading"]}\n'
                     f'- [{text["home_label"]}]({origin}/)\n'),
            "fill_in": [text["business_name"],
                        text["business_description"]],
        }
    # وما عدا ذلك لا يُخترع له علاج. خريطةُ الموقع تحتاج زحفاً لا نجريه عمداً،
    # والعنوانُ وH1 نصّان يكتبهما صاحبُ الصفحة ولا يُملَيان من خارجها.
    return None


NO_REMEDY_REASON = {
    "en": {
        "sitemap": ("a sitemap must list your real pages; generating one would "
                    "require crawling your site, which this read-only check "
                    "deliberately does not do"),
        "title": ("a page title is your own wording; a generated one would be "
                  "worse than the gap"),
        "h1": ("a primary heading is your own wording; a generated one would "
               "be worse than the gap"),
        "robots": ("a robots policy depends on what you intend to expose; "
                   "guessing it could hide pages you want found"),
        "jsonld_valid": ("the existing JSON-LD block must be corrected in "
                         "place; adding a second generated block would leave "
                         "the invalid one and would not close this miss"),
        "home": ("the page did not load, so there is nothing to paste into "
                 "it yet"),
    },
    "ar": {
        "sitemap": ("خريطة الموقع يجب أن تسرد صفحاتك الحقيقية؛ توليدها يتطلب "
                    "زحفاً لا ينفذه هذا الفحص المقروء فقط"),
        "title": "عنوان الصفحة صياغتك أنت؛ اختلاقه أسوأ من ترك النقص",
        "h1": "العنوان الرئيس صياغتك أنت؛ اختلاقه أسوأ من ترك النقص",
        "robots": ("سياسة robots تتبع ما تريد إظهاره؛ تخمينها قد يحجب صفحات "
                   "تريد فهرستها"),
        "jsonld_valid": ("يجب تصحيح كتلة JSON-LD القائمة في موضعها؛ إضافة "
                         "كتلة ثانية تترك الخاطئة ولا تغلق العطل"),
        "home": "الصفحة لم تُحمّل، لذلك لا يوجد بعد موضع تُلصق فيه معالجة",
    },
}


def explain_gap(signal_key: str, language: str = "en") -> str | None:
    """لماذا لا علاجَ جاهزاً لهذه الإشارة — يُقال ولا يُسكَت عنه."""
    return NO_REMEDY_REASON.get(language, {}).get(signal_key)


def selftest() -> int:
    fails: list[str] = []
    URL = "https://shop.example.com/products/x?q=1"

    # ١) العلاجُ يُبنى على الأصل الذي سلّمه المتّصل، ولا يحمل مسارَه ولا معاملاته.
    r = remedy_for("structured_business", URL)
    if not r or "https://shop.example.com" not in r["code"]:
        fails.append("العلاجُ لا يحمل أصلَ المتّصل")
    for leak in ("/products/x", "q=1"):
        if r and leak in r["code"]:
            fails.append(f"العلاجُ سرّب مسارَ الصفحة أو معاملاتِها: {leak}")

    # ٢) ولا يُصدَّر إلا JSON صالح — كتلةٌ لا تُحلَّل ليست علاجاً.
    for key in ("structured_business", "structured_offering"):
        code = remedy_for(key, URL)["code"]
        body = code.split(">", 1)[1].rsplit("<", 1)[0].strip()
        try:
            parsed = json.loads(body)
        except Exception as exc:                                  # noqa: BLE001
            fails.append(f"{key}: الكتلةُ ليست JSON صالحاً: {exc}")
            continue
        if parsed.get("@context") != "https://schema.org":
            fails.append(f"{key}: بلا @context صحيح")

    # ٣) وكلُّ موضعٍ يُملأ معلَنٌ في fill_in — فحقلٌ يبقى NAME في صفحةٍ حيّةٍ
    #    أسوأُ من غيابه، ولا يُترك اكتشافُه للصدفة.
    for key in ("structured_business", "structured_offering", "canonical",
                "description", "llms_txt"):
        for language in ("ar", "en"):
            r = remedy_for(key, URL, language)
            if not r["fill_in"]:
                fails.append(f"{key}/{language}: بلا fill_in وفيه مواضعُ ملء")
            for hole in r["fill_in"]:
                if hole not in r["code"]:
                    fails.append(
                        f"{key}/{language}: موضعُ ملء غير موجود في الكود: {hole}"
                    )

    # ٤) وما لا يُغلق بكتلةٍ لا يُخترع له علاج، ويُقال سببُه.
    for key in ("sitemap", "title", "h1", "robots", "jsonld_valid", "home"):
        if remedy_for(key, URL) is not None:
            fails.append(f"{key}: اختُرع له علاجٌ وهو لا يُغلق بكتلةٍ تُلصق")
        for language in ("ar", "en"):
            if not explain_gap(key, language):
                fails.append(
                    f"{key}/{language}: بلا علاجٍ وبلا سببٍ معلَن — صمتٌ لا إفصاح"
                )

    # ٥) وأصلٌ غيرُ آمنٍ يرسب ولا يُبنى عليه.
    for bad in ("https:///", "ftp://x.test/", "",
                "https://[::1]:99999/"):
        try:
            remedy_for("structured_business", bad)
            fails.append(f"أصلٌ غيرُ صالحٍ مرّ: {bad!r}")
        except ValueError:
            pass

    # ٦) وكلُّ بروتوكولٍ تقبله الأداة العامة يُنتج العلاجَ نفسه على أصلِه.
    for scheme in ("http", "https"):
        for language in ("ar", "en"):
            out = remedy_for(
                "structured_business", f"{scheme}://x.test/p?q=1", language
            )
            if not out or f'"url": "{scheme}://x.test/"' not in out["code"]:
                fails.append(
                    f"أصلٌ عامٌّ مقبولٌ لم يُنتج علاجاً: {scheme}/{language}"
                )
    if not re.search(r"[\u0600-\u06ff]", remedy_for(
            "structured_business", URL, "ar")["where"]):
        fails.append("تعليماتُ موضع العلاج العربي لم تُوطَّن")
    if not re.search(r"[\u0600-\u06ff]", explain_gap("jsonld_valid", "ar") or ""):
        fails.append("سببُ غياب علاج JSON-LD العربي لم يُوطَّن")
    llms_ar = remedy_for("llms_txt", URL, "ar")["code"]
    if "## الصفحات" not in llms_ar or "[الرئيسية]" not in llms_ar:
        fails.append("قالبُ llms.txt العربي يحمل عناوين إنجليزية")

    # ٧) وحقنٌ في **المسار** لا يتسرّب، لأنّ الأصلَ وحدَه يُؤخذ. هذه ليست
    #    حالةَ رسوب: العنوانُ صالحٌ وأصلُه نظيف، والمطلوبُ إثباتُ أنّ حمولتَه
    #    لا تظهر في المخرَج.
    hostile = 'https://x.test/"><script>alert(1)</script>'
    out = remedy_for("structured_business", hostile)
    if out is None or out["code"].count("https://x.test") == 0:
        fails.append("عنوانٌ صالحٌ بمسارٍ عدائيٍّ رُفض بدل أن يُنظَّف أصلُه")
    elif "script>alert" in out["code"] or '"><' in out["code"]:
        fails.append("حمولةُ المسار العدائيّ تسرّبت إلى كتلةٍ تُلصق")

    # ٨) ومضيفٌ يحمل محرفَ اقتباسٍ لا يتسرّب إلى كتلةٍ تُلصق في HTML.
    for key in ("structured_business", "canonical", "llms_txt"):
        code = remedy_for(key, URL)["code"]
        if '"><' in code or "</script" in code.replace("</script>", ""):
            fails.append(f"{key}: الكتلةُ تحمل كسرَ سياقٍ محتملاً")

    if fails:
        print("SELFTEST FAIL:")
        for f in fails:
            print("  -", f)
        return 1
    print("SELFTEST PASS (العلاجُ من أصلِ المتّصل لا من جسد صفحته · وJSON "
          "صالحٌ · وكلُّ موضعِ ملءٍ معلَن · وما لا يُغلق لا يُخترع له علاجٌ "
          "ويُقال سببُه · والأصلُ غيرُ الآمن يرسب)")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="الكتلةُ التي تُغلق العطل")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--signal")
    ap.add_argument("--url")
    ap.add_argument("--lang", choices=("ar", "en"), default="en")
    a = ap.parse_args(argv)
    if a.selftest:
        return selftest()
    if not (a.signal and a.url):
        ap.error("--signal و--url معاً، أو --selftest")
    r = remedy_for(a.signal, a.url, a.lang)
    if r is None:
        print(json.dumps({"remedy": None,
                          "why": explain_gap(a.signal, a.lang)},
                         ensure_ascii=False, indent=2))
        return 0
    print(json.dumps(r, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
