# Generated from the maintained Advisors AI server sources.
# Report issues in this repository; do not edit this file directly.
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""One read-only MCP tool for an explicitly requested public-page check.

This is deliberately a third server.  It does not register anything on the
five-tool ``/mcp`` service navigator and it exposes no catalogue, price,
request, order, payment, or invitation field.  The same application can be
run for the Claude connector, the MCP Registry, or the isolated OpenAI
surface; the surface is fixed by server configuration, never by tool input.
"""
from __future__ import annotations

import ipaddress
import json
import os
import sys
import threading
import time
from collections import OrderedDict, deque
from pathlib import Path
from typing import Annotated, Any, Literal

from mcp.server import MCPServer
from mcp.server.context import CallNext, HandlerResult, ServerRequestContext
from mcp.server.transport_security import (
    TransportSecurityMiddleware,
    TransportSecuritySettings,
)
from mcp.shared.exceptions import MCPError
from mcp.types import INVALID_PARAMS, ToolAnnotations
from pydantic import BaseModel, ConfigDict, Field, ValidationError
from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.types import ASGIApp, Receive, Scope, Send



VERSION = "1.0.6"
MCP_PATH = "/store-readiness-mcp"
RECHECK_PATH = "/store-readiness/recheck"
HEALTH_PATH = "/store-readiness-healthz"
INTERNAL_HEALTH_PATH = "/healthz"
TOOL_NAME = "advisors_store_readiness_check"
MAX_RECHECK_BODY_BYTES = 32 * 1024


def _positive_setting(name: str, default: int, maximum: int) -> int:
    raw = os.environ.get(name, str(default)).strip()
    try:
        value = int(raw)
    except ValueError as exc:
        raise RuntimeError(f"{name} must be an integer") from exc
    if not 1 <= value <= maximum:
        raise RuntimeError(f"{name} is outside the approved range")
    return value


RATE_LIMIT_REQUESTS = _positive_setting(
    "ADVISORS_STORE_READINESS_RATE_LIMIT_REQUESTS", 12, 10_000)
RATE_LIMIT_WINDOW_SECONDS = _positive_setting(
    "ADVISORS_STORE_READINESS_RATE_LIMIT_WINDOW_SECONDS", 60, 3_600)
RATE_LIMIT_MAX_CLIENTS = 2_048
SURFACES = frozenset({
    "claude-connector",
    "mcp-registry",
    "openai-isolated",
})
SURFACE = os.environ.get(
    "ADVISORS_STORE_READINESS_SURFACE", "mcp-registry"
).strip().lower()
if SURFACE not in SURFACES:
    raise RuntimeError("ADVISORS_STORE_READINESS_SURFACE is not approved")


Language = Literal["ar", "en"]
PublicUrl = Annotated[
    str,
    Field(
        min_length=4,
        max_length=2_048,
        description=(
            "A credential-free public HTTP(S) page. Private networks and "
            "non-standard web ports are rejected."
        ),
        examples=["https://example.com/store"],
    ),
]


class StrictModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_alias=True,
        validate_by_name=True,
        serialize_by_alias=True,
    )


class LegacyAttestationOutput(StrictModel):
    scheme: Literal["entity-hmac-sha256-v1"]
    kind: str
    payload_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    signature: str = Field(pattern=r"^[0-9a-f]{64}$")


class AttestationOutput(StrictModel):
    scheme: Literal["entity-hmac-sha256-v2"]
    kind: str
    key_id: str = Field(pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
    policy_version: str = Field(pattern=r"^\d{4}-\d{2}-\d{2}\.\d+$")
    payload_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    signature: str = Field(pattern=r"^[0-9a-f]{64}$")


AttestationEnvelopeOutput = LegacyAttestationOutput | AttestationOutput


class SignedPermissionFields(StrictModel):
    scan_public_url: Literal[True]
    display_to_requester: Literal[True]
    store_result: Literal[False]
    share_result: Literal[False]
    aggregate_result: Literal[False]


class SourceReceiptOutput(SignedPermissionFields):
    schema_: Literal["advisorsai.transient_receipt/v1"] = Field(alias="schema")
    receipt_id: str
    source_token: str
    target_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    target_origin: str
    measurement_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    check_schema: Literal["almanzoma.public_readiness_check/v2"]
    measurement: Literal["declared_public_page_machine_basics"]
    signal_key: str
    result: Literal["miss"]
    score_percent: int = Field(ge=0, le=100)
    coverage_percent: int = Field(ge=0, le=100)
    measured_at_utc: str
    language: Language
    purpose: Literal["transient-public-page-proof"]
    surface: Literal[
        "claude-connector", "mcp-registry", "openai-isolated"
    ]
    issued_at_utc: str
    expires_at_utc: str
    delete_at_utc: str
    attestation: AttestationEnvelopeOutput


class ConsentReceiptOutput(SignedPermissionFields):
    schema_: Literal["advisorsai.transient_receipt/v1"] = Field(alias="schema")
    receipt_id: str
    consent_state: Literal["request-submitted"]
    purpose: Literal["transient-public-page-check"]
    target_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    target_origin: str
    language: Language
    surface: Literal[
        "claude-connector", "mcp-registry", "openai-isolated"
    ]
    issued_at_utc: str
    expires_at_utc: str
    delete_at_utc: str
    attestation: AttestationEnvelopeOutput


class MethodologyReferenceOutput(StrictModel):
    point: int = Field(ge=1, le=30)
    relation: Literal["partial"]


class FindingOutput(StrictModel):
    signal_key: str
    label: str
    methodology_reference: MethodologyReferenceOutput | None


class ProvenanceOutput(StrictModel):
    """من قاس، وأين بقيّةُ القياس.

    قِيس 2026-08-23 أنّ المخرَج لا يحمل إلى المستخدم شيئاً سوى `recheck_url`
    وهو مسارُ آلةٍ لا وجهةُ إنسان: مساعدٌ ينادي الأداةَ فيرى المستخدمُ عطلاً
    واحداً، ولا يعرف من قاسه ولا أنّ تسعَ إشاراتٍ أخرى قِيست. فالاكتشافُ
    يتحوّل إلى صفرٍ بحكم البناء لا بحكم قلّة الطلب.

    وهذا **إسنادٌ لا إعلان**: اسمُ من قاس، ورابطُ الورقة الكاملة، وعددُ ما
    قِيس وما يُعاد منه. لا وعدَ ترتيبٍ ولا ذكرٍ ولا نيّةِ شراء — تلك يمنعها
    عقدُ الأداة، ولا يمسّها هذا الحقل.
    """
    measured_by: Literal["Advisors AI"] = "Advisors AI"
    full_sheet_url: str
    signals_measured: int = Field(ge=1)
    signals_returned: int = Field(ge=1)


class RemedyOutput(StrictModel):
    """الكتلةُ التي تُغلق العطل — لا وصفُه.

    قِيس 2026-08-24 أنّ المخرَج يحمل `imperative` و`acceptance` ولا يحمل
    علاجاً: نقول «ينقصك بيانٌ منظَّم» ونترك العميلَ يكتبه. وهذا تقريرٌ بثوبِ
    أداة، ويخالف `docs/مبدأ-الإصلاح-لا-التقرير.md`.

    ولا يُبنى العلاجُ من جسد الصفحة: مخرَجُنا يدخل سياقَ مساعدٍ ذكيّ، والصفحةُ
    المجلوبةُ مدخلٌ لا نملكه. فالمواضعُ تُترك للعميل يملؤها، ولا يُصدَّر منها
    إلا الأصلُ الذي سلّمه المتّصلُ بنفسه.
    """
    closes: str
    format: Literal["html-head-block", "new-file"]
    where: str
    code: str
    fill_in: list[str]


class EvidenceOutput(StrictModel):
    measurement: str
    result: Literal["miss"]
    score_percent: int = Field(ge=0, le=100)
    coverage_percent: int = Field(ge=0, le=100)
    measured_at_utc: str


ToolStatus = Literal[
    "finding",
    "ready",
    "no_actionable_finding",
    "partial",
    "target_rejected",
    "check_unavailable",
    "proof_unavailable",
]
ProofStatus = Literal["verified", "not_applicable", "unavailable"]


class StoreReadinessOutput(StrictModel):
    schema_: Literal["advisors.store-readiness-tool/v1"] = Field(alias="schema")
    ok: bool
    status: ToolStatus
    measurement_status: str
    proof_status: ProofStatus
    surface: Literal[
        "claude-connector", "mcp-registry", "openai-isolated"
    ]
    language: Language
    target: str | None = None
    finding: FindingOutput | None = None
    evidence: EvidenceOutput | None = None
    imperative: str | None = None
    acceptance: str | None = None
    remedy: RemedyOutput | None = None
    no_remedy_reason: str | None = None
    recheck_url: str | None = None
    provenance: ProvenanceOutput | None = None
    consent_receipt: ConsentReceiptOutput | None = None
    source_receipt: SourceReceiptOutput | None = None
    measurement: str | None = None
    score_percent: int | None = Field(default=None, ge=0, le=100)
    coverage_percent: int | None = Field(default=None, ge=0, le=100)
    errors: list[str] = Field(default_factory=list)
    not_measured: list[str] = Field(default_factory=list)


class RecheckInput(StrictModel):
    url: PublicUrl
    source_receipt: SourceReceiptOutput
    language: Language = "ar"


class RecheckErrorOutput(StrictModel):
    ok: Literal[False]
    status: Literal[
        "invalid_request", "receipt_rejected", "proof_unavailable"
    ]
    error: str


def _proof_module():
    """Import the concurrently developed proof contract only when invoked."""
    from . import proof_capsule
    return proof_capsule


def _measure_public_page(url: str, language: Language) -> dict[str, Any]:
    """Enter the proof module through its URL-only trust boundary."""
    module = _proof_module()
    measure = getattr(module, "measure_public_page", None)
    if not callable(measure):
        raise RuntimeError("trusted measurement entry point is unavailable")
    result = measure(url, surface=SURFACE, language=language)
    if not isinstance(result, dict) or set(result) != {
        "check", "capsule", "proof_status",
    }:
        raise RuntimeError("trusted measurement result is not closed")
    if result.get("proof_status") not in {
        "verified", "not_applicable", "unavailable",
    }:
        raise RuntimeError("trusted measurement proof state is invalid")
    return result


def _validate_proof(cap: dict[str, Any]) -> list[str]:
    module = _proof_module()
    validator = getattr(module, "validate", None)
    if not callable(validator):
        return ["proof_validator_unavailable"]
    result = validator(cap, surface=SURFACE)
    return list(result or [])


def _base_result(check: dict[str, Any], *, status: ToolStatus,
                 proof_status: ProofStatus, ok: bool,
                 language: Language = "ar",
                 errors: list[str] | None = None) -> dict[str, Any]:
    return {
        "schema": "advisors.store-readiness-tool/v1",
        "ok": ok,
        "status": status,
        "measurement_status": str(check.get("status") or "check_unavailable"),
        "proof_status": proof_status,
        "surface": SURFACE,
        "language": language,
        # Until an HMAC-authenticated capsule is available, expose only the
        # public origin;
        # the exact path remains transient checker input rather than output.
        "target": check.get("checked_origin"),
        "finding": None,
        "evidence": None,
        "imperative": None,
        "acceptance": None,
        "recheck_url": None,
        "provenance": _provenance(check, language),
        "consent_receipt": None,
        "source_receipt": None,
        "measurement": check.get("measurement"),
        "score_percent": check.get("score_percent"),
        "coverage_percent": check.get("coverage_percent"),
        "errors": list(errors or []),
        "not_measured": list(check.get("not_measured") or []),
    }


# صفحةُ الورقة الكاملة بلغة الطالب. إرسالُ قارئٍ إنجليزيّ إلى صفحةٍ عربيّة
# ضياعٌ لا إسناد، فالرابطُ يتبع اللغة المطلوبة.
# كان الإنجليزيُّ يُحال إلى صفحةِ الخدمات التفافاً، لأنّ `en-readiness-sheet.html`
# كانت ترجع **404** (قِيس 2026-08-23) وإرسالُ عميلٍ إلى صفحةٍ ميتةٍ أسوأُ من
# ألّا نُرسله. **ونُشرت الصفحةُ 2026-08-24 فرجعت 200**، فرصدها
# `outbound_live_guard` كما بُني ليفعل، فأُزيل الالتفافُ وعادت الوجهةُ الصحيحة.
# قياسٌ حيٌّ عليها بأداتنا نفسِها لحظةَ الإعادة: 100/100 بتغطية 100%.
FULL_SHEET_URL = {
    "ar": "https://advisorsai.ai/readiness-sheet.html",
    "en": "https://advisorsai.ai/en-readiness-sheet.html",
}
# الوجهةُ المقصودةُ حين تُنشر — يقيسها الحارسُ ويُنبّه إلى استعادتها.
INTENDED_EN_SHEET = "https://advisorsai.ai/en-readiness-sheet.html"


def _remedy_rows(signal_key: str,
                 target: str,
                 language: Language = "ar") -> tuple[RemedyOutput | None, str | None]:
    """يرجع (العلاج، سببَ غيابه). ولا يُسقط قياسةً صحيحةً حين يتعذّر العلاج.

    فالعلاجُ إضافةٌ فوق القياس لا شرطٌ له: عطلٌ في مولّد العلاج يجب أن يكلّف
    العميلَ كتلةَ لصقٍ لا نتيجتَه كلَّها.
    """
    unavailable = {
        "ar": "تعذّر توليد معالجة جاهزة للصق بأمان لهذه النتيجة",
        "en": "a paste-ready remedy could not be generated safely for this result",
    }[language]
    try:
        from . import readiness_remedy as rr
    except Exception:                                             # noqa: BLE001
        return None, unavailable
    try:
        raw = rr.remedy_for(signal_key, target, language)
    except Exception:                                             # noqa: BLE001
        return None, unavailable
    if raw is None:
        return None, (rr.explain_gap(signal_key, language) or unavailable)
    try:
        return RemedyOutput.model_validate(raw), None
    except ValidationError:
        return None, unavailable


def _provenance(check: dict[str, Any],
                language: Language = "ar") -> dict[str, Any] | None:
    """يُبنى من عدد الإشارات المقيسة فعلاً، لا من رقمٍ مكتوبٍ بيد.

    رقمٌ ثابتٌ في النصّ يكذب صامتاً أوّلَ ما تُضاف إشارةٌ أو تُحذف.
    """
    signals = check.get("signals")
    count = len(signals) if isinstance(signals, (list, dict)) else None
    if not count:
        return None
    return {
        "measured_by": "Advisors AI",
        "full_sheet_url": FULL_SHEET_URL.get(language, FULL_SHEET_URL["ar"]),
        "signals_measured": count,
        "signals_returned": 1,
    }


def _closed_measurement_result(
    check: dict[str, Any], language: Language,
) -> StoreReadinessOutput:
    status = str(check.get("status") or "check_unavailable")
    if status == "partial":
        row = _base_result(
            check, status="partial", proof_status="not_applicable",
            ok=False, language=language, errors=["measurement_partial"],
        )
    elif status == "target_rejected":
        row = _base_result(
            check, status="target_rejected", proof_status="not_applicable",
            ok=False, language=language,
            errors=list(check.get("errors") or ["target_rejected"]),
        )
    else:
        row = _base_result(
            check, status="check_unavailable", proof_status="not_applicable",
            ok=False, language=language, errors=["measurement_unavailable"],
        )
    return StoreReadinessOutput.model_validate(row)


def _normalise_capsule(
    check: dict[str, Any], cap: dict[str, Any], language: Language,
) -> StoreReadinessOutput:
    problems = _validate_proof(cap)
    if problems:
        raise RuntimeError("proof capsule validation failed")
    evidence_row = cap.get("evidence")
    finding_row = cap.get("finding")
    signals = {
        signal.get("key"): signal
        for signal in check.get("signals", [])
        if isinstance(signal, dict)
    }
    chosen = (
        signals.get(finding_row.get("signal_key"))
        if isinstance(finding_row, dict) else None
    )
    if (
        cap.get("surface") != SURFACE
        or cap.get("language") != language
        or cap.get("target") != check.get("checked_origin")
        or not isinstance(evidence_row, dict)
        or evidence_row.get("measurement") != check.get("measurement")
        or evidence_row.get("score_percent") != check.get("score_percent")
        or evidence_row.get("coverage_percent") != check.get("coverage_percent")
        or evidence_row.get("measured_at_utc") != check.get("measured_at_utc")
        or not isinstance(chosen, dict)
        or chosen.get("ok") is not False
        or not isinstance(chosen.get("weight"), int)
        or chosen["weight"] <= 0
    ):
        raise RuntimeError("proof capsule does not match its measurement")
    source_receipt = SourceReceiptOutput.model_validate(
        cap.get("source_receipt"))
    consent_receipt = ConsentReceiptOutput.model_validate(
        cap.get("consent_receipt"))
    finding = FindingOutput.model_validate(cap.get("finding"))
    evidence = EvidenceOutput.model_validate(evidence_row)
    row = _base_result(
        check, status="finding", proof_status="verified", ok=True,
        language=cap.get("language"),
    )
    # العلاجُ يُبنى على **أصلِ ما قِيس** لا على ما ورد في الطلب، فيبقى
    # مقيَّداً بما أثبتته القياسةُ نفسُها.
    remedy, why = _remedy_rows(
        finding.signal_key,
        str(cap.get("target") or ""),
        language,
    )
    row.update({
        "target": cap.get("target"),
        "finding": finding,
        "evidence": evidence,
        "imperative": cap.get("imperative"),
        "acceptance": cap.get("acceptance"),
        "remedy": remedy,
        "no_remedy_reason": why,
        "recheck_url": cap.get("recheck_url"),
        "consent_receipt": consent_receipt,
        "source_receipt": source_receipt,
    })
    return StoreReadinessOutput.model_validate(row)


def advisors_store_readiness_check(
    url: str,
    language: Language = "ar",
) -> StoreReadinessOutput:
    """Measure once, then build one verified proof capsule or fail closed."""
    try:
        measured = _measure_public_page(url, language)
    except Exception:  # public boundary: never expose an internal exception
        return _closed_measurement_result(
            {"status": "check_unavailable"}, language)

    check = measured.get("check")
    if not isinstance(check, dict):
        return _closed_measurement_result(
            {"status": "check_unavailable"}, language)
    if check.get("status") != "complete":
        return _closed_measurement_result(check, language)

    try:
        cap = measured.get("capsule")
        measured_proof_status = measured.get("proof_status")
        if measured_proof_status == "unavailable":
            if cap is not None:
                raise RuntimeError("unavailable proof carried a capsule")
            return StoreReadinessOutput.model_validate(_base_result(
                check, status="proof_unavailable", proof_status="unavailable",
                ok=False, language=language, errors=["proof_unavailable"],
            ))
        if cap is None:
            if measured_proof_status != "not_applicable":
                raise RuntimeError("proof state and capsule disagree")
            status: ToolStatus = (
                "ready" if check.get("readiness_passed") is True
                else "no_actionable_finding"
            )
            return StoreReadinessOutput.model_validate(_base_result(
                check, status=status, proof_status="not_applicable", ok=True,
                language=language,
            ))
        if not isinstance(cap, dict):
            raise RuntimeError("proof capsule returned a non-object")
        if measured_proof_status != "verified":
            raise RuntimeError("unverified proof capsule")
        return _normalise_capsule(check, cap, language)
    except Exception:
        # Missing signing material, a temporarily absent proof API, or a
        # malformed proof all have the same safe public result.  Exception
        # text is never reflected to the agent or merchant.
        return StoreReadinessOutput.model_validate(_base_result(
            check, status="proof_unavailable", proof_status="unavailable",
            ok=False, language=language, errors=["proof_unavailable"],
        ))


class StrictToolArguments:
    """Reject undeclared arguments before the SDK can discard them."""

    ERROR = "undeclared tool arguments are not allowed"

    def __init__(self, allowed: dict[str, frozenset[str]]):
        self.allowed = dict(allowed)

    async def __call__(self, ctx: ServerRequestContext,
                       call_next: CallNext) -> HandlerResult:
        if ctx.method == "tools/call" and isinstance(ctx.params, dict):
            name = str(ctx.params.get("name") or "")
            arguments = ctx.params.get("arguments") or {}
            expected = self.allowed.get(name)
            if expected is not None and isinstance(arguments, dict):
                if set(arguments) - expected:
                    raise MCPError(
                        code=INVALID_PARAMS,
                        message=self.ERROR,
                        data={"reason": "undeclared_arguments"},
                    )
        return await call_next(ctx)


TOOL_ARGUMENTS = {
    TOOL_NAME: frozenset({"url", "language"}),
}
ANNOTATIONS = ToolAnnotations(
    readOnlyHint=True,
    destructiveHint=False,
    idempotentHint=True,
    openWorldHint=True,
)


mcp = MCPServer(
    name="advisors-ai-store-readiness",
    title="Advisors AI Store Readiness Check",
    description=(
        "One read-only check of declared machine-readable basics on a "
        "requester-supplied public page."
    ),
    instructions=(
        f"Expose only {TOOL_NAME}. Call it only when the requester asks to "
        "inspect a public HTTP(S) page. Never infer ranking, mentions, buyer "
        "intent, sales, or ownership. Return only the bounded measurement "
        "and its verification receipts."
    ),
    version=VERSION,
    middleware=[StrictToolArguments(TOOL_ARGUMENTS)],
)


@mcp.tool(
    name=TOOL_NAME,
    title="Check one public store page for one actionable readiness finding",
    description=(
        "Use only after the requester supplies a public page and asks for a "
        "read-only check. Returns at most one measured finding with a "
        "server-authenticated source receipt and the fixed acceptance "
        "condition."
    ),
    annotations=ANNOTATIONS,
    structured_output=True,
)
def tool_store_readiness(
    url: PublicUrl,
    language: Annotated[
        Language, Field(description="Response language: ar or en.")
    ] = "ar",
) -> StoreReadinessOutput:
    return advisors_store_readiness_check(url, language)


def _seal_input_contract() -> None:
    manager = mcp._tool_manager  # MCP SDK 2.0; dependency is pinned.
    registered = {tool.name for tool in manager.list_tools()}
    if registered != set(TOOL_ARGUMENTS):
        raise RuntimeError("store readiness tool inventory is not closed")
    tool = manager.get_tool(TOOL_NAME)
    if tool is None:
        raise RuntimeError("store readiness tool is unavailable")
    if set(tool.parameters.get("properties", {})) != TOOL_ARGUMENTS[TOOL_NAME]:
        raise RuntimeError("store readiness input fields drifted")
    tool.fn_metadata.arg_model.model_config["extra"] = "forbid"
    tool.fn_metadata.arg_model.model_rebuild(force=True)
    tool.parameters = tool.fn_metadata.arg_model.model_json_schema(by_alias=True)
    if tool.parameters.get("additionalProperties") is not False:
        raise RuntimeError("store readiness input schema is not closed")


_seal_input_contract()


@mcp.custom_route(HEALTH_PATH, methods=["GET"], include_in_schema=False)
@mcp.custom_route(
    INTERNAL_HEALTH_PATH, methods=["GET"], include_in_schema=False)
async def healthz(_request: Request) -> JSONResponse:
    return JSONResponse({
        "ok": True,
        "service": "advisors-ai-store-readiness",
        "version": VERSION,
        "surface": SURFACE,
        "tool_count": 1,
        "write_tools": 0,
        "recheck_method": "POST",
        "local_rate_limit": {
            "active": True,
            "max_requests": RATE_LIMIT_REQUESTS,
            "window_seconds": RATE_LIMIT_WINDOW_SECONDS,
            "protected_paths": [MCP_PATH, RECHECK_PATH],
            "scope": "per-client",
            "client_identity": (
                "socket-peer; cf-connecting-ip only from loopback proxy"
            ),
        },
        "edge_rate_limit_recommended": True,
    })


def _pairs_without_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    obj: dict[str, Any] = {}
    for key, value in pairs:
        if key in obj:
            raise ValueError("duplicate JSON key")
        obj[key] = value
    return obj


def _error_response(status: Literal[
        "invalid_request", "receipt_rejected", "proof_unavailable"],
        error: str, http_status: int) -> JSONResponse:
    row = RecheckErrorOutput(ok=False, status=status, error=error)
    return JSONResponse(row.model_dump(mode="json"), status_code=http_status)


@mcp.custom_route(RECHECK_PATH, methods=["POST"], include_in_schema=False)
async def recheck(request: Request) -> JSONResponse:
    content_type = request.headers.get("content-type", "").split(";", 1)[0]
    if content_type.strip().lower() != "application/json":
        return _error_response(
            "invalid_request", "application_json_required", 415)
    length = request.headers.get("content-length")
    if length:
        try:
            if int(length) > MAX_RECHECK_BODY_BYTES:
                return _error_response(
                    "invalid_request", "request_body_too_large", 413)
        except ValueError:
            return _error_response(
                "invalid_request", "invalid_content_length", 400)
    body = await request.body()
    if len(body) > MAX_RECHECK_BODY_BYTES:
        return _error_response(
            "invalid_request", "request_body_too_large", 413)
    try:
        payload = json.loads(
            body.decode("utf-8"), object_pairs_hook=_pairs_without_duplicates)
        parsed = RecheckInput.model_validate(payload)
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError, ValidationError):
        return _error_response("invalid_request", "closed_contract_required", 400)

    try:
        module = _proof_module()
        verifier = getattr(module, "verify_recheck_request", None)
        if not callable(verifier):
            raise RuntimeError("recheck verifier unavailable")
        verified = verifier(
            parsed.url,
            parsed.source_receipt.model_dump(mode="json"),
            language=parsed.language,
        )
    except (RuntimeError, TypeError, ValueError):
        return _error_response("proof_unavailable", "proof_unavailable", 503)
    if verified is not True:
        return _error_response("receipt_rejected", "receipt_rejected", 403)

    result = advisors_store_readiness_check(parsed.url, parsed.language)
    return JSONResponse(result.model_dump(mode="json"))


class LocalRateLimit:
    """Small fixed-window guard for the two public, scan-triggering paths.

    It uses the socket peer address. ``CF-Connecting-IP`` is accepted only
    from a loopback peer, so a direct remote caller cannot mint buckets by
    spoofing a forwarding header.  The two limits are runtime-configurable
    for a deployment whose reverse proxy does not share the loopback network.
    """

    def __init__(
        self,
        app: ASGIApp,
        *,
        max_requests: int = RATE_LIMIT_REQUESTS,
        window_seconds: int = RATE_LIMIT_WINDOW_SECONDS,
    ) -> None:
        if max_requests < 1 or window_seconds < 1:
            raise ValueError("rate limit must be positive")
        self.app = app
        self.max_requests = max_requests
        self.window_seconds = window_seconds
        self._buckets: OrderedDict[str, deque[float]] = OrderedDict()
        self._lock = threading.Lock()

    @staticmethod
    def _client_identity(scope: Scope) -> str:
        peer = scope.get("client")
        peer_text = str(peer[0]) if isinstance(peer, tuple) and peer else ""
        try:
            peer_address = ipaddress.ip_address(peer_text)
            peer_key = peer_address.compressed
        except ValueError:
            return "peer:unknown"

        if peer_address.is_loopback:
            forwarded = [
                value for name, value in scope.get("headers", [])
                if name.lower() == b"cf-connecting-ip"
            ]
            if len(forwarded) == 1:
                try:
                    candidate = ipaddress.ip_address(
                        forwarded[0].decode("ascii").strip())
                except (UnicodeDecodeError, ValueError):
                    candidate = None
                if candidate is not None and candidate.is_global:
                    return "cf:" + candidate.compressed
        return "peer:" + peer_key

    def _admit(self, client: str, moment: float) -> tuple[bool, int]:
        cutoff = moment - self.window_seconds
        with self._lock:
            expired = [
                key for key, values in self._buckets.items()
                if not values or values[-1] <= cutoff
            ]
            for key in expired:
                self._buckets.pop(key, None)
            if client not in self._buckets:
                if len(self._buckets) >= RATE_LIMIT_MAX_CLIENTS:
                    client = "__overflow__"
                self._buckets.setdefault(client, deque())
            values = self._buckets[client]
            while values and values[0] <= cutoff:
                values.popleft()
            self._buckets.move_to_end(client)
            if len(values) >= self.max_requests:
                retry_after = max(
                    1,
                    int(self.window_seconds - (moment - values[0])) + 1,
                )
                return False, retry_after
            values.append(moment)
            return True, 0

    async def __call__(
        self, scope: Scope, receive: Receive, send: Send,
    ) -> None:
        path = str(scope.get("path") or "").rstrip("/") or "/"
        protected = {MCP_PATH.rstrip("/"), RECHECK_PATH.rstrip("/")}
        if scope.get("type") != "http" or path not in protected:
            await self.app(scope, receive, send)
            return
        client = self._client_identity(scope)
        allowed, retry_after = self._admit(client, time.monotonic())
        if allowed:
            await self.app(scope, receive, send)
            return
        response = JSONResponse(
            {
                "ok": False,
                "status": "rate_limited",
                "error": "rate_limit_exceeded",
            },
            status_code=429,
            headers={"Retry-After": str(retry_after)},
        )
        await response(scope, receive, send)


class PostOnlyMCPTransport:
    """Reject dead standalone streams on this stateless MCP endpoint.

    The Python SDK 2.0 legacy transport still opens an indefinite SSE stream
    for a version-less ``GET`` even when ``stateless_http=True``.  This service
    has no session or server-initiated channel to feed such a stream, so the
    Streamable HTTP contract requires an immediate 405 instead.  Keep the
    gate outside the rate limiter: unsupported probes neither occupy a live
    connection nor consume a caller's POST allowance.
    """

    def __init__(
        self,
        app: ASGIApp,
        security_settings: TransportSecuritySettings,
    ) -> None:
        self.app = app
        self.security = TransportSecurityMiddleware(security_settings)

    async def __call__(
        self, scope: Scope, receive: Receive, send: Send,
    ) -> None:
        is_mcp = (
            scope.get("type") == "http"
            and scope.get("path") == MCP_PATH
        )
        if is_mcp:
            method = str(scope.get("method") or "").upper()
            request = Request(scope, receive=receive)
            rejection = await self.security.validate_request(
                request, is_post=(method == "POST"))
            if rejection is not None:
                await rejection(scope, receive, send)
                return
        if is_mcp and method != "POST":
            response = Response(
                content=b"",
                status_code=405,
                headers={"Allow": "POST"},
            )
            await response(scope, receive, send)
            return
        await self.app(scope, receive, send)


TRANSPORT_SECURITY = TransportSecuritySettings(
    allowed_hosts=[
        "advisorsai.ai",
        "advisorsai.ai:*",
        "localhost",
        "localhost:*",
        "127.0.0.1",
        "127.0.0.1:*",
    ],
    # Exact browser origins for the three intended surfaces.  Server-to-server
    # MCP clients normally omit Origin; unknown browser origins stay closed.
    allowed_origins=[
        "https://advisorsai.ai",
        "https://claude.ai",
        "https://chatgpt.com",
    ],
)

_transport_app = mcp.streamable_http_app(
    streamable_http_path=MCP_PATH,
    json_response=True,
    stateless_http=True,
    max_request_body_size=128 * 1024,
    transport_security=TRANSPORT_SECURITY,
    host="0.0.0.0",
)
app = PostOnlyMCPTransport(
    LocalRateLimit(_transport_app), TRANSPORT_SECURITY)


if __name__ == "__main__":
    print(
        "Run the published package with: "
        "python -m uvicorn advisorsai_mcp.server:app "
        "--host 127.0.0.1 --port 8773"
    )
    raise SystemExit(2)
